/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DDialogLotInStock.java
 *
 * Created on 7/11/2011, 07:51:51 PM
 */

package sba.mod.trn.form;

import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.Vector;
import sba.gui.util.DUtilConsts;
import sba.lib.DLibConsts;
import sba.lib.DLibTimeUtils;
import sba.lib.DLibUtils;
import sba.lib.db.DDbRegistry;
import sba.lib.grid.DGridColumnForm;
import sba.lib.grid.DGridConsts;
import sba.lib.grid.DGridPaneForm;
import sba.lib.grid.DGridPaneFormOwner;
import sba.lib.grid.DGridRow;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanFormDialog;
import sba.mod.DModConsts;
import sba.mod.DModSysConsts;
import sba.mod.itm.db.DDbItem;
import sba.mod.itm.db.DDbUnit;
import sba.mod.trn.db.DRowLot;
import sba.mod.trn.db.DTrnStockMove;

/**
 *
 * @author Sergio Flores
 */
public class DDialogLotInStock extends DBeanFormDialog implements DGridPaneFormOwner {

    private Date mtDate;
    private int mnYear;
    private int[] manItemUnitKey;
    private int[] manWarehouseKey;
    private int[] manBookkeepingNumberKey;
    private DDbItem moItem;
    private DDbUnit moUnit;
    private Vector<DTrnStockMove> mvStockMovesToAdjust;
    private Vector<DTrnStockMove> mvStockMoves;
    private DGridPaneForm moGridLots;

    /** Creates new form DDialogLotInStock
     * @param client GUI client.
     */
    public DDialogLotInStock(DGuiClient client) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, DModConsts.TX_STK_LOT, DLibConsts.UNDEFINED, "Lotes disponibles");
        initComponents();
        initComponentsCustom();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGroup = new javax.swing.ButtonGroup();
        jpPanelItem = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlQuantity = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtfCode = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jtfQuantity = new javax.swing.JTextField();
        jtfUnitCode = new javax.swing.JTextField();
        jpPanelCentral = new javax.swing.JPanel();
        jpItemsSouth = new javax.swing.JPanel();
        jtfBranchCode = new javax.swing.JTextField();
        jtfBranchWarehouseCode = new javax.swing.JTextField();
        jtfYear = new javax.swing.JTextField();

        jpPanelItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        jpPanelItem.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jPanel1.setLayout(new java.awt.FlowLayout(0, 5, 0));

        jlCode.setText("Código ítem:");
        jlCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(jlCode);

        jlName.setText("Nombre ítem:");
        jlName.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel1.add(jlName);

        jlQuantity.setText("Cantidad:");
        jlQuantity.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel1.add(jlQuantity);

        jpPanelItem.add(jPanel1);

        jPanel3.setLayout(new java.awt.FlowLayout(0, 5, 0));

        jtfCode.setEditable(false);
        jtfCode.setText("CODE");
        jtfCode.setToolTipText("Código");
        jtfCode.setFocusable(false);
        jtfCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jtfCode);

        jtfName.setEditable(false);
        jtfName.setText("NAME");
        jtfName.setToolTipText("Nombre");
        jtfName.setFocusable(false);
        jtfName.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel3.add(jtfName);

        jtfQuantity.setEditable(false);
        jtfQuantity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfQuantity.setText("0");
        jtfQuantity.setFocusable(false);
        jtfQuantity.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel3.add(jtfQuantity);

        jtfUnitCode.setEditable(false);
        jtfUnitCode.setText("UN");
        jtfUnitCode.setFocusable(false);
        jtfUnitCode.setPreferredSize(new java.awt.Dimension(30, 23));
        jPanel3.add(jtfUnitCode);

        jpPanelItem.add(jPanel3);

        getContentPane().add(jpPanelItem, java.awt.BorderLayout.NORTH);

        jpPanelCentral.setPreferredSize(new java.awt.Dimension(100, 100));
        jpPanelCentral.setLayout(new java.awt.BorderLayout(0, 5));

        jpItemsSouth.setLayout(new java.awt.FlowLayout(2, 5, 0));

        jtfBranchCode.setEditable(false);
        jtfBranchCode.setToolTipText(DUtilConsts.TXT_BRANCH);
        jtfBranchCode.setFocusable(false);
        jtfBranchCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpItemsSouth.add(jtfBranchCode);

        jtfBranchWarehouseCode.setEditable(false);
        jtfBranchWarehouseCode.setToolTipText(DUtilConsts.TXT_BRANCH_WAH);
        jtfBranchWarehouseCode.setFocusable(false);
        jtfBranchWarehouseCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpItemsSouth.add(jtfBranchWarehouseCode);

        jtfYear.setEditable(false);
        jtfYear.setToolTipText(DUtilConsts.TXT_FISCAL_YEAR);
        jtfYear.setFocusable(false);
        jtfYear.setPreferredSize(new java.awt.Dimension(50, 23));
        jpItemsSouth.add(jtfYear);

        jpPanelCentral.add(jpItemsSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jpPanelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsCustom() {
        DGuiUtils.setWindowBounds(this, 640, 400);

        mvStockMovesToAdjust = new Vector<DTrnStockMove>();
        mvStockMoves = new Vector<DTrnStockMove>();

        jbSave.setText(DGuiConsts.TXT_BTN_OK);

        moGridLots = new DGridPaneForm(miClient, mnFormType, mnFormSubtype, true, msTitle) {

            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }

            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[3];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DATE, "Caducidad");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_M, "Lote");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Cantidad");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };

        moGridLots.setForm(null);
        moGridLots.setPaneFormOwner(this);

        jpPanelCentral.add(moGridLots, BorderLayout.CENTER);

        mvFormGrids.add(moGridLots);
    }

    @Override
    protected void windowActivated() {
        if (mbFirstActivation) {
            mbFirstActivation = false;
            moGridLots.getTable().requestFocus();
        }
    }

    private void renderDate() {
        jtfYear.setText(DLibUtils.DecimalFormatCalendarYear.format(mnYear));
    }

    private void renderBranchWarehouse() {
        jtfBranchCode.setText((String) miClient.getSession().readField(DModConsts.BU_BRA, new int[] { manWarehouseKey[0], manWarehouseKey[1] }, DDbRegistry.FIELD_CODE));
        jtfBranchWarehouseCode.setText((String) miClient.getSession().readField(DModConsts.CU_WAH, manWarehouseKey, DDbRegistry.FIELD_CODE));
    }

    private void renderItem() {
        if (moItem == null) {
            jtfCode.setText("");
            jtfName.setText("");

            jtfCode.setToolTipText(DGuiConsts.TXT_LBL_CODE);
            jtfName.setToolTipText(DGuiConsts.TXT_LBL_NAME);
        }
        else {
            jtfCode.setText(moItem.getCode());
            jtfName.setText(moItem.getName());

            jtfCode.setToolTipText(DGuiConsts.TXT_LBL_CODE + ": " + moItem.getCode());
            jtfName.setToolTipText(DGuiConsts.TXT_LBL_NAME + ": " + moItem.getName());
        }

        jtfCode.setCaretPosition(0);
        jtfName.setCaretPosition(0);
    }

    private void renderUnit() {
        if (moUnit == null) {
            jtfUnitCode.setText("");

            jtfUnitCode.setToolTipText(DGuiConsts.TXT_LBL_UNIT);
        }
        else {
            jtfUnitCode.setText(moUnit.getCode());

            jtfUnitCode.setToolTipText(DGuiConsts.TXT_LBL_UNIT + ": " + moUnit.getCode());
        }

        jtfUnitCode.setCaretPosition(0);
    }

    private void renderStockMoves() {
        double quantity = 0;
        String sql = "";
        ResultSet resultSet = null;
        Vector<DTrnStockMove> moves = new Vector<DTrnStockMove>();
        Vector<DTrnStockMove> movesFound = new Vector<DTrnStockMove>();
        Vector<DGridRow> lots = new Vector<DGridRow>();

        try {
            if (mvStockMovesToAdjust.size() > 0) {
                for (DTrnStockMove stockMove : mvStockMovesToAdjust) {
                    movesFound.add(stockMove.clone());
                }
            }
            else {
                if (manItemUnitKey != null && manWarehouseKey != null) {
                    // Get serial numbers in stock:

                    sql = "SELECT l.id_lot, l.dt_exp_n, l.lot, SUM(mov_in - mov_out) AS f_stk " +
                            "FROM " + DModConsts.TablesMap.get(DModConsts.T_STK) + " AS s " +
                            "INNER JOIN " + DModConsts.TablesMap.get(DModConsts.T_LOT) + " AS l ON " +
                            "s.id_itm = l.id_itm AND s.id_unt = l.id_unt AND s.id_lot = l.id_lot " +
                            "WHERE s.b_del = 0 AND s.id_yer = " + mnYear + " AND " +
                            "s.id_itm = " + manItemUnitKey[0] + " AND s.id_unt = " + manItemUnitKey[1] + " AND " +
                            "s.id_bpr = " + manWarehouseKey[0] + " AND s.id_bra = " + manWarehouseKey[1] + " AND s.id_wah = " + manWarehouseKey[2] + " " +
                            (manBookkeepingNumberKey == null ? "" : "AND NOT (s.fk_bkk_yer_n = " + manBookkeepingNumberKey[0] + " AND s.fk_bkk_num_n = " + manBookkeepingNumberKey[1] + ") ") +
                            "GROUP BY l.id_lot, l.dt_exp_n, l.lot " +
                            "HAVING f_stk <> 0 " +
                            "ORDER BY l.dt_exp_n, l.lot, l.id_lot ";
                    resultSet = miClient.getSession().getStatement().executeQuery(sql);
                    while (resultSet.next()) {
                        DTrnStockMove move = new DTrnStockMove(
                                new int[] { manItemUnitKey[0], manItemUnitKey[1], resultSet.getInt("l.id_lot"), manWarehouseKey[0], manWarehouseKey[1], manWarehouseKey[2] },
                                resultSet.getDouble("f_stk"), "", "", null, resultSet.getString("l.lot"), resultSet.getDate("l.dt_exp_n"));
                        movesFound.add(move);
                    }
                }
            }

            // Exclude stock lots allready selected:

            FOUND:
            for (DTrnStockMove moveFound : movesFound) {
                for (DTrnStockMove move : mvStockMoves) {
                    if (moveFound.getLot().compareTo(move.getLot()) == 0) {
                        moveFound.setQuantity(moveFound.getQuantity() - move.getQuantity());
                        break;
                    }
                }

                if (moveFound.getQuantity() != 0) {
                    moves.add(moveFound);
                }
            }

            for (DTrnStockMove move : moves) {
                quantity += move.getQuantity();
                lots.add(new DRowLot(move));
            }

            moGridLots.populateGrid(lots);
            jtfQuantity.setText(DLibUtils.getDecimalFormatQuantity().format(quantity));
            jtfQuantity.setCaretPosition(0);
        }
        catch (SQLException e) {
            DLibUtils.showException(this, e);
        }
        catch (Exception e) {
            DLibUtils.showException(this, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jButtonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlQuantity;
    private javax.swing.JPanel jpItemsSouth;
    private javax.swing.JPanel jpPanelCentral;
    private javax.swing.JPanel jpPanelItem;
    private javax.swing.JTextField jtfBranchCode;
    private javax.swing.JTextField jtfBranchWarehouseCode;
    private javax.swing.JTextField jtfCode;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfQuantity;
    private javax.swing.JTextField jtfUnitCode;
    private javax.swing.JTextField jtfYear;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addAllListeners() {

    }

    @Override
    public void removeAllListeners() {

    }

    @Override
    public void reloadCatalogues() {

    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public DDbRegistry getRegistry() throws Exception {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public DGuiValidation validateForm() {
        DGuiValidation validation = new DGuiValidation();

        if (moGridLots.getSelectedGridRow() == null) {
            validation.setMessage(DGuiConsts.ERR_MSG_UNDEF_OPTION);
            validation.setComponent(moGridLots.getTable());
        }

        return validation;
    }

    @Override
    public void resetForm() {
        removeAllListeners();
        reloadCatalogues();

        mnFormResult = DLibConsts.UNDEFINED;
        mbFirstActivation = true;

        mtDate = null;
        mnYear = 0;
        manItemUnitKey = null;
        manWarehouseKey = null;
        manBookkeepingNumberKey = null;
        moItem = null;
        moUnit = null;
        mvStockMovesToAdjust.clear();
        mvStockMoves.clear();

        renderItem();
        renderUnit();
        renderStockMoves();

        addAllListeners();
    }

    @Override
    @SuppressWarnings("unchecked")
    public void setValue(final int type, final Object value) {
        switch (type) {
            case DModSysConsts.PARAM_DATE:
                mtDate = (Date) value;
                mnYear = DLibTimeUtils.digestYear(mtDate)[0];
                renderDate();
                break;
            case DModSysConsts.PARAM_ITM_UNT:
                manItemUnitKey = (int[]) value;
                moItem = (DDbItem) miClient.getSession().readRegistry(DModConsts.IU_ITM, new int[] { manItemUnitKey[0] });
                moUnit = (DDbUnit) miClient.getSession().readRegistry(DModConsts.IU_UNT, new int[] { manItemUnitKey[1] });
                renderItem();
                renderUnit();
                break;
            case DModSysConsts.PARAM_BRA_WAH:
                manWarehouseKey = (int[]) value;
                renderBranchWarehouse();
                break;
            case DModSysConsts.PARAM_BKK_NUM_KEY:
                manBookkeepingNumberKey = (int[]) value;
                break;
            case DModSysConsts.PARAM_VEC_STK_MOV_ADJ:
                mvStockMovesToAdjust.addAll((Vector<DTrnStockMove>) value);
                break;
            case DModSysConsts.PARAM_VEC_STK_MOV:
                mvStockMoves.addAll((Vector<DTrnStockMove>) value);
                renderStockMoves();
                break;
            default:
                miClient.showMsgBoxError(DLibConsts.ERR_MSG_OPTION_UNKNOWN);
        }
    }

    @Override
    public Object getValue(final int type) {
        Object value = null;

        switch (type) {
            case DModSysConsts.PARAM_OBJ_STK_MOV:
                value = ((DRowLot) moGridLots.getSelectedGridRow()).getStockMove();
                break;
            default:
                miClient.showMsgBoxError(DLibConsts.ERR_MSG_OPTION_UNKNOWN);
        }

        return value;
    }

    @Override
    public void notifyRowNew(int gridType, int gridSubtype, int row, DGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void notifyRowEdit(int gridType, int gridSubtype, int row, DGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void notifyRowDelete(int gridType, int gridSubtype, int row, DGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
