/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DDialogDpsDiscount.java
 *
 * Created on 7/11/2011, 07:51:51 PM
 */

package sba.mod.trn.form;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import sba.lib.DLibConsts;
import sba.lib.db.DDbRegistry;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiItem;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanFieldRadio;
import sba.lib.gui.bean.DBeanFormDialog;
import sba.mod.DModConsts;
import sba.mod.DModSysConsts;
import sba.mod.cfg.db.DDbConfigCompany;

/**
 *
 * @author Sergio Flores
 */
public class DDialogDpsItemPriceTypePicker extends DBeanFormDialog implements ItemListener {
    
    public static final int PARAM_BPR_ITM_PRC_TP = 1;
    public static final int PARAM_EFF_ITM_PRC_TP = 2;
    
    private int mnBizPartnerItemPriceType;
    private ArrayList<DGuiItem> maPriceTypes;

    /** Creates new form DDialogDpsDiscount
     * @param client GUI client.
     */
    public DDialogDpsItemPriceTypePicker(DGuiClient client) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, DLibConsts.UNDEFINED, DLibConsts.UNDEFINED, "Tipo de precios del documento");
        initComponents();
        initComponentsCustom();
        
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPriceTypesOptions = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        moRadItemPriceTypeBizPartner = new sba.lib.gui.bean.DBeanFieldRadio();
        jtfItemPriceTypeBizPartner = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        moRadItemPriceTypeCustom = new sba.lib.gui.bean.DBeanFieldRadio();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jlItemPriceTypes = new javax.swing.JLabel();
        jspItemPriceTypes = new javax.swing.JScrollPane();
        jlstItemPriceTypes = new javax.swing.JList();

        setTitle("Descuento del documento:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección de tipo de precios:"));
        jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        bgPriceTypesOptions.add(moRadItemPriceTypeBizPartner);
        moRadItemPriceTypeBizPartner.setText("Precios del asociado de negocios");
        moRadItemPriceTypeBizPartner.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel1.add(moRadItemPriceTypeBizPartner);

        jtfItemPriceTypeBizPartner.setEditable(false);
        jtfItemPriceTypeBizPartner.setText("TEXT");
        jtfItemPriceTypeBizPartner.setFocusable(false);
        jtfItemPriceTypeBizPartner.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel1.add(jtfItemPriceTypeBizPartner);

        jPanel3.add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        bgPriceTypesOptions.add(moRadItemPriceTypeCustom);
        moRadItemPriceTypeCustom.setText("Seleccionar otro tipo de precios");
        moRadItemPriceTypeCustom.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel4.add(moRadItemPriceTypeCustom);

        jPanel3.add(jPanel4);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlItemPriceTypes.setText("Tipos de precios disponibles:");
        jlItemPriceTypes.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel6.add(jlItemPriceTypes);

        jPanel5.add(jPanel6, java.awt.BorderLayout.NORTH);

        jspItemPriceTypes.setViewportView(jlstItemPriceTypes);

        jPanel5.add(jspItemPriceTypes, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsCustom() {
        DGuiUtils.setWindowBounds(this, 480, 300);

        moRadItemPriceTypeBizPartner.setBooleanSettings(moRadItemPriceTypeBizPartner.getText(), true);
        moRadItemPriceTypeCustom.setBooleanSettings(moRadItemPriceTypeCustom.getText(), false);

        moFields.addField(moRadItemPriceTypeBizPartner);
        moFields.addField(moRadItemPriceTypeCustom);
        moFields.setFormButton(jbSave);

        jbSave.setText(DGuiConsts.TXT_BTN_OK);
    }

    @SuppressWarnings("unchecked")
    private void populateItemPriceTypes() {
        DDbConfigCompany configCompany = (DDbConfigCompany) miClient.getSession().getConfigCompany();
        
        maPriceTypes = new ArrayList<>();
        
        if (configCompany.isPriceSrpApplying()) {
            maPriceTypes.add(new DGuiItem(new int[] { DModSysConsts.MS_ITM_PRC_TP_SRP },
                (String) miClient.getSession().readField(DModConsts.MS_ITM_PRC_TP, new int[] { DModSysConsts.MS_ITM_PRC_TP_SRP }, DDbRegistry.FIELD_NAME)));
        }
        if (configCompany.isPrice1Applying()) {
            maPriceTypes.add(new DGuiItem(new int[] { DModSysConsts.MS_ITM_PRC_TP_RET },
                (String) miClient.getSession().readField(DModConsts.MS_ITM_PRC_TP, new int[] { DModSysConsts.MS_ITM_PRC_TP_RET }, DDbRegistry.FIELD_NAME)));
        }
        if (configCompany.isPrice2Applying()) {
            maPriceTypes.add(new DGuiItem(new int[] { DModSysConsts.MS_ITM_PRC_TP_HAL },
                (String) miClient.getSession().readField(DModConsts.MS_ITM_PRC_TP, new int[] { DModSysConsts.MS_ITM_PRC_TP_HAL }, DDbRegistry.FIELD_NAME)));
        }
        if (configCompany.isPrice3Applying()) {
            maPriceTypes.add(new DGuiItem(new int[] { DModSysConsts.MS_ITM_PRC_TP_WHO },
                (String) miClient.getSession().readField(DModConsts.MS_ITM_PRC_TP, new int[] { DModSysConsts.MS_ITM_PRC_TP_WHO }, DDbRegistry.FIELD_NAME)));
        }
        if (configCompany.isPrice4Applying()) {
            maPriceTypes.add(new DGuiItem(new int[] { DModSysConsts.MS_ITM_PRC_TP_ESP },
                (String) miClient.getSession().readField(DModConsts.MS_ITM_PRC_TP, new int[] { DModSysConsts.MS_ITM_PRC_TP_ESP }, DDbRegistry.FIELD_NAME)));
        }
        if (configCompany.isPrice5Applying()) {
            maPriceTypes.add(new DGuiItem(new int[] { DModSysConsts.MS_ITM_PRC_TP_COS },
                (String) miClient.getSession().readField(DModConsts.MS_ITM_PRC_TP, new int[] { DModSysConsts.MS_ITM_PRC_TP_COS }, DDbRegistry.FIELD_NAME)));
        }
        
        jlstItemPriceTypes.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return maPriceTypes.size(); }
            public Object getElementAt(int i) { return maPriceTypes.get(i); }
        });
        
        /*
        jlstItemPriceTypes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "a", "b", "c", "d", "e" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        */
    }
    
    private void selectItemPriceType(int itemPriceType) {
        int index = -1;
        
        for (int element = 0; element < jlstItemPriceTypes.getModel().getSize(); element++) {
            if (((DGuiItem) jlstItemPriceTypes.getModel().getElementAt(element)).getPrimaryKey()[0] == itemPriceType) {
                index = element;
                break;
            }
        }

        if (index == -1) {
            jlstItemPriceTypes.clearSelection();
        }
        else {
            jlstItemPriceTypes.setSelectedIndex(index);
        }
    }
    
    private void setBizPartnerItemPriceType(int itemPriceType) {
        mnBizPartnerItemPriceType = itemPriceType;
        
        jtfItemPriceTypeBizPartner.setText((String) miClient.getSession().readField(DModConsts.MS_ITM_PRC_TP, new int[] { mnBizPartnerItemPriceType }, DDbRegistry.FIELD_NAME));
        jtfItemPriceTypeBizPartner.setCaretPosition(0);
    }
    
    private void setEffectiveItemPriceType(int itemPriceType) {
        if (itemPriceType == mnBizPartnerItemPriceType) {
            if (!moRadItemPriceTypeBizPartner.isSelected()) {
                moRadItemPriceTypeBizPartner.setSelected(true); // it will trigger item event
            }
        }
        else {
            if (!moRadItemPriceTypeCustom.isSelected()) {
                moRadItemPriceTypeCustom.setSelected(true); // it will trigger item event
            }
            
            selectItemPriceType(itemPriceType);
        }
    }
    
    private int getItemPriceType() {
        int itemPriceType = DLibConsts.UNDEFINED;
        
        if (moRadItemPriceTypeCustom.isSelected()) {
            if (jlstItemPriceTypes.getSelectedIndex() >= 0) {
                itemPriceType = ((DGuiItem) jlstItemPriceTypes.getModel().getElementAt(jlstItemPriceTypes.getSelectedIndex())).getPrimaryKey()[0];
            }
        }
        
        return itemPriceType;
    }
    
    private void itemStateChangedItemPriceType() {
        if (moRadItemPriceTypeBizPartner.isSelected()) {
            jlstItemPriceTypes.setEnabled(false);
            
            jlstItemPriceTypes.clearSelection();
        }
        else {
            jlstItemPriceTypes.setEnabled(true);
            
            selectItemPriceType(mnBizPartnerItemPriceType);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPriceTypesOptions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlItemPriceTypes;
    private javax.swing.JList jlstItemPriceTypes;
    private javax.swing.JScrollPane jspItemPriceTypes;
    private javax.swing.JTextField jtfItemPriceTypeBizPartner;
    private sba.lib.gui.bean.DBeanFieldRadio moRadItemPriceTypeBizPartner;
    private sba.lib.gui.bean.DBeanFieldRadio moRadItemPriceTypeCustom;
    // End of variables declaration//GEN-END:variables
    
    public void initForm() {
        removeAllListeners();
        reloadCatalogues();
        addAllListeners();
    }

    public void resetForm() {
        mnFormResult = DLibConsts.UNDEFINED;
        mbFirstActivation = true;
        
        moRadItemPriceTypeBizPartner.setSelected(true);
        jlstItemPriceTypes.clearSelection();
    }
    
    @Override
    public void addAllListeners() {
        moRadItemPriceTypeBizPartner.addItemListener(this);
        moRadItemPriceTypeCustom.addItemListener(this);
    }

    @Override
    public void removeAllListeners() {
        moRadItemPriceTypeBizPartner.removeItemListener(this);
        moRadItemPriceTypeCustom.removeItemListener(this);
    }

    @Override
    public void reloadCatalogues() {
        populateItemPriceTypes();
    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public DDbRegistry getRegistry() throws Exception {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public DGuiValidation validateForm() {
        DGuiValidation validation = moFields.validateFields();
        
        if (moRadItemPriceTypeCustom.isSelected()) {
            if (jlstItemPriceTypes.getSelectedIndex() < 0) {
                validation.setMessage(DGuiConsts.ERR_MSG_FIELD_REQ + "'" + DGuiUtils.getLabelName(jlItemPriceTypes) + "'.");
                validation.setComponent(jlstItemPriceTypes);
            }
        }

        return validation;
    }

    @Override
    public void setValue(final int type, final Object value) {
        switch (type) {
            case PARAM_BPR_ITM_PRC_TP:
                setBizPartnerItemPriceType((int) value);
                break;
            case PARAM_EFF_ITM_PRC_TP:
                setEffectiveItemPriceType((int) value);
                break;
            default:
                miClient.showMsgBoxError(DLibConsts.ERR_MSG_OPTION_UNKNOWN);
        }
    }

    @Override
    public Object getValue(final int type) {
        Object value = null;

        switch (type) {
            case DModConsts.MS_ITM_PRC_TP:
                value = getItemPriceType();
                break;
            default:
                miClient.showMsgBoxError(DLibConsts.ERR_MSG_OPTION_UNKNOWN);
        }

        return value;
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof DBeanFieldRadio && e.getStateChange() == ItemEvent.SELECTED) {
            DBeanFieldRadio field = (DBeanFieldRadio) e.getSource();
            if (field == moRadItemPriceTypeBizPartner || field == moRadItemPriceTypeCustom) {
                itemStateChangedItemPriceType();
            }
        }
    }
}
