/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sba.mod.lad.form;

import cfd.ver40.DCfdi40Catalogs;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JTable;
import sba.gui.cat.DXmlCatalog;
import sba.gui.cat.DXmlCatalogEntry;
import sba.lib.DLibUtils;
import sba.lib.db.DDbRegistry;
import sba.lib.grid.DGridColumnForm;
import sba.lib.grid.DGridConsts;
import sba.lib.grid.DGridPaneForm;
import sba.lib.grid.DGridRow;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanFieldText;
import sba.lib.gui.bean.DBeanFormDialog;
import sba.mod.lad.db.DLadCatalogAddressCountry;
import sba.mod.lad.db.DLadCatalogAddressCounty;
import sba.mod.lad.db.DLadCatalogAddressDistrict;
import sba.mod.lad.db.DLadCatalogAddressLocality;
import sba.mod.lad.db.DLadCatalogAddressState;
import sba.mod.lad.db.DLadCatalogConsts;

/**
 *
 * @author Sergio Flores
 */
public class DPickerCatalogAddressDistrict extends DBeanFormDialog implements ActionListener, KeyListener {
    
    protected DLadCatalogAddressCountry moCountry;
    protected DLadCatalogAddressState moState;
    protected DLadCatalogAddressCounty moCounty;
    protected DLadCatalogAddressLocality moLocality;
    protected String msZipCode;
    protected String msOldZipCode;
    protected DGridPaneForm moGridOptions;
    protected ArrayList<DGridRow> maGridRows;

    /**
     * Creates new form DPickerAddressDistrict
     */
    public DPickerCatalogAddressDistrict(DGuiClient client) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, 0, 0, "Buscar colonia");
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpParams = new javax.swing.JPanel();
        jpParams1 = new javax.swing.JPanel();
        jlCountry = new javax.swing.JLabel();
        jtfCountryCode = new javax.swing.JTextField();
        jtfCountryName = new javax.swing.JTextField();
        jpParams2 = new javax.swing.JPanel();
        jlState = new javax.swing.JLabel();
        jtfStateCode = new javax.swing.JTextField();
        jtfStateName = new javax.swing.JTextField();
        jpParams4 = new javax.swing.JPanel();
        jlCounty = new javax.swing.JLabel();
        jtfCountyCode = new javax.swing.JTextField();
        jtfCountyName = new javax.swing.JTextField();
        jpParams5 = new javax.swing.JPanel();
        jlLocality = new javax.swing.JLabel();
        jtfLocalityCode = new javax.swing.JTextField();
        jtfLocalityName = new javax.swing.JTextField();
        jlZipCode = new javax.swing.JLabel();
        jtfZipCode = new javax.swing.JTextField();
        jpParams3 = new javax.swing.JPanel();
        jlDistrict = new javax.swing.JLabel();
        moTextDistrictName = new sba.lib.gui.bean.DBeanFieldText();
        moTextDistrictCode = new sba.lib.gui.bean.DBeanFieldText();
        jbClear = new javax.swing.JButton();
        jpOptions = new javax.swing.JPanel();

        jpParams.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros de búsqueda:"));
        jpParams.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        jpParams1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCountry.setText("País:");
        jlCountry.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams1.add(jlCountry);

        jtfCountryCode.setEditable(false);
        jtfCountryCode.setText("TEXT");
        jtfCountryCode.setFocusable(false);
        jtfCountryCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams1.add(jtfCountryCode);

        jtfCountryName.setEditable(false);
        jtfCountryName.setText("TEXT");
        jtfCountryName.setFocusable(false);
        jtfCountryName.setPreferredSize(new java.awt.Dimension(400, 23));
        jpParams1.add(jtfCountryName);

        jpParams.add(jpParams1);

        jpParams2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlState.setText("Estado:");
        jlState.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams2.add(jlState);

        jtfStateCode.setEditable(false);
        jtfStateCode.setText("TEXT");
        jtfStateCode.setFocusable(false);
        jtfStateCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams2.add(jtfStateCode);

        jtfStateName.setEditable(false);
        jtfStateName.setText("TEXT");
        jtfStateName.setFocusable(false);
        jtfStateName.setPreferredSize(new java.awt.Dimension(400, 23));
        jpParams2.add(jtfStateName);

        jpParams.add(jpParams2);

        jpParams4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCounty.setText("Municipio:");
        jlCounty.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams4.add(jlCounty);

        jtfCountyCode.setEditable(false);
        jtfCountyCode.setText("TEXT");
        jtfCountyCode.setFocusable(false);
        jtfCountyCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams4.add(jtfCountyCode);

        jtfCountyName.setEditable(false);
        jtfCountyName.setText("TEXT");
        jtfCountyName.setFocusable(false);
        jtfCountyName.setPreferredSize(new java.awt.Dimension(400, 23));
        jpParams4.add(jtfCountyName);

        jpParams.add(jpParams4);

        jpParams5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlLocality.setText("Localidad:");
        jlLocality.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams5.add(jlLocality);

        jtfLocalityCode.setEditable(false);
        jtfLocalityCode.setText("TEXT");
        jtfLocalityCode.setFocusable(false);
        jtfLocalityCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams5.add(jtfLocalityCode);

        jtfLocalityName.setEditable(false);
        jtfLocalityName.setText("TEXT");
        jtfLocalityName.setFocusable(false);
        jtfLocalityName.setPreferredSize(new java.awt.Dimension(300, 23));
        jpParams5.add(jtfLocalityName);

        jlZipCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlZipCode.setText("CP:");
        jlZipCode.setPreferredSize(new java.awt.Dimension(35, 23));
        jpParams5.add(jlZipCode);

        jtfZipCode.setEditable(false);
        jtfZipCode.setText("000000000000");
        jtfZipCode.setFocusable(false);
        jtfZipCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jpParams5.add(jtfZipCode);

        jpParams.add(jpParams5);

        jpParams3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDistrict.setText("Colonia:");
        jlDistrict.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams3.add(jlDistrict);

        moTextDistrictName.setText("TEXT");
        moTextDistrictName.setPreferredSize(new java.awt.Dimension(400, 23));
        jpParams3.add(moTextDistrictName);

        moTextDistrictCode.setText("TEXT");
        moTextDistrictCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams3.add(moTextDistrictCode);

        jbClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/gui/img/cmd_std_delete.gif"))); // NOI18N
        jbClear.setToolTipText("Limpiar");
        jbClear.setPreferredSize(new java.awt.Dimension(23, 23));
        jpParams3.add(jbClear);

        jpParams.add(jpParams3);

        getContentPane().add(jpParams, java.awt.BorderLayout.NORTH);

        jpOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones:"));
        jpOptions.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jpOptions, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClear;
    private javax.swing.JLabel jlCountry;
    private javax.swing.JLabel jlCounty;
    private javax.swing.JLabel jlDistrict;
    private javax.swing.JLabel jlLocality;
    private javax.swing.JLabel jlState;
    private javax.swing.JLabel jlZipCode;
    private javax.swing.JPanel jpOptions;
    private javax.swing.JPanel jpParams;
    private javax.swing.JPanel jpParams1;
    private javax.swing.JPanel jpParams2;
    private javax.swing.JPanel jpParams3;
    private javax.swing.JPanel jpParams4;
    private javax.swing.JPanel jpParams5;
    private javax.swing.JTextField jtfCountryCode;
    private javax.swing.JTextField jtfCountryName;
    private javax.swing.JTextField jtfCountyCode;
    private javax.swing.JTextField jtfCountyName;
    private javax.swing.JTextField jtfLocalityCode;
    private javax.swing.JTextField jtfLocalityName;
    private javax.swing.JTextField jtfStateCode;
    private javax.swing.JTextField jtfStateName;
    private javax.swing.JTextField jtfZipCode;
    private sba.lib.gui.bean.DBeanFieldText moTextDistrictCode;
    private sba.lib.gui.bean.DBeanFieldText moTextDistrictName;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        DGuiUtils.setWindowBounds(this, 640, 400);
        
        moTextDistrictName.setTextSettings(DGuiUtils.getLabelName(jlState), 100);
        moTextDistrictName.setTextCaseType(0);
        moTextDistrictCode.setTextSettings(DGuiUtils.getLabelName(jlState), DBolUtils.DEF_CODE_ADDRESS_DISTRICT.length());
        moTextDistrictCode.setTextCaseType(0);
        
        moFields.addField(moTextDistrictName);
        moFields.addField(moTextDistrictCode);
        moFields.setFormButton(jbSave);
        
        moGridOptions = new DGridPaneForm(miClient, mnFormType, mnFormSubtype, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[2];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT, "Descripción", 400);
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT, "Clave", 100);

                for (DGridColumnForm column : columns) {
                    moModel.getGridColumns().add(column);
                }
            }
        };
        
        jpOptions.add(moGridOptions, BorderLayout.CENTER);
    }
    
    private void populateGridOptions(final Vector<DGridRow> rows) {
        moGridOptions.populateGrid(rows);
        moGridOptions.getTable().addKeyListener(this);
        moGridOptions.getTable().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    actionSave();
                }
            }
        });
    }
    
    private void actionPerformedClear() {
        moTextDistrictName.resetField();
        moTextDistrictCode.resetField();
        
        moTextDistrictName.requestFocus();
    }

    private void keyPressedDistrictCode(final KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.VK_ENTER) {
            event.consume();
            moGridOptions.getTable().requestFocusInWindow();
        }
    }
    
    private void keyPressedTable(final KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.VK_ENTER && moGridOptions.getSelectedGridRow() != null) {
            event.consume();
            actionSave();
        }
    }

    private void keyReleasedDistrictNameCode(final KeyEvent e) {
        String name = moTextDistrictName.getValue().toUpperCase();
        String code = moTextDistrictCode.getValue().toUpperCase();
        Vector<DGridRow> rows = new Vector<>();
        
        if (name.isEmpty() && code.isEmpty()) {
            rows.addAll(maGridRows);
        }
        else {
            for (DGridRow row : maGridRows) {
                if ((!name.isEmpty() && row.getRowName().toUpperCase().contains(name)) || (!code.isEmpty() && row.getRowCode().toUpperCase().contains(code))) {
                    rows.add(row);
                }
            }
        }
        
        populateGridOptions(rows);
    }
    
    @Override
    public void resetForm() {
        mnFormResult = 0;
        mbFirstActivation = true;
        
        removeAllListeners();
        
        moFields.resetFields();
        
        try {
            if (msOldZipCode == null || msOldZipCode.isEmpty() || !msOldZipCode.equals(msZipCode)) {
                msOldZipCode = msZipCode;
                
                maGridRows = new ArrayList<>();
                boolean found = false;
                DXmlCatalog xmlCatalog = DBolUtils.getXmlCatalog(DCfdi40Catalogs.XML_CCP_COL + "_" + DLibUtils.textLeft(msZipCode, 1), DBolUtils.ATT_ZIP, "", null);
                for (DXmlCatalogEntry entry : xmlCatalog.getEntries()) {
                    if (entry.getBelongingCode().equals(msZipCode)) {
                        found = true;
                        maGridRows.add(new DLadCatalogAddressDistrict(entry.getCode(), entry.getName()));
                    }
                    else if (found) {
                        break; // stop when found zip code changes
                    }
                }
                
                if (maGridRows.isEmpty()) {
                    miClient.showMsgBoxWarning("No se encontraron colonias para el CP '" + msZipCode + "'.");
                }
            }
            
            populateGridOptions(new Vector<>(maGridRows));
        }
        catch (Exception e) {
            DLibUtils.showException(this, e);
        }
        
        addAllListeners();
    }
    
    @Override
    public void addAllListeners() {
        jbClear.addActionListener(this);
        moTextDistrictName.addKeyListener(this);
        moTextDistrictCode.addKeyListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbClear.removeActionListener(this);
        moTextDistrictName.removeKeyListener(this);
        moTextDistrictCode.removeKeyListener(this);
    }

    @Override
    public void reloadCatalogues() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public DDbRegistry getRegistry() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public DGuiValidation validateForm() {
        DGuiValidation validation = new DGuiValidation();
        
        if (moGridOptions.getSelectedGridRow() == null) {
            validation.setMessage(DGridConsts.MSG_SELECT_ROW);
            validation.setComponent(moGridOptions.getTable());
        }
        
        return validation;
    }
    
    private void setCountry(final DLadCatalogAddressCountry country) {
        moCountry = country;
        
        if (moCountry == null) {
            jtfCountryCode.setText("");
            jtfCountryName.setText("");
        }
        else {
            jtfCountryCode.setText(moCountry.Code);
            jtfCountryCode.setCaretPosition(0);
            jtfCountryName.setText(moCountry.Name);
            jtfCountryName.setCaretPosition(0);
        }
    }
    
    private void setState(final DLadCatalogAddressState state) {
        moState = state;
        
        if (moState == null) {
            jtfStateCode.setText("");
            jtfStateName.setText("");
        }
        else {
            jtfStateCode.setText(moState.Code);
            jtfStateCode.setCaretPosition(0);
            jtfStateName.setText(moState.Name);
            jtfStateName.setCaretPosition(0);
        }
    }
    
    private void setCounty(final DLadCatalogAddressCounty county) {
        moCounty = county;
        
        if (moCounty == null) {
            jtfCountyCode.setText("");
            jtfCountyName.setText("");
        }
        else {
            jtfCountyCode.setText(moCounty.Code);
            jtfCountyCode.setCaretPosition(0);
            jtfCountyName.setText(moCounty.Name);
            jtfCountyName.setCaretPosition(0);
        }
    }
    
    private void setLocality(final DLadCatalogAddressLocality locality) {
        moLocality = locality;
        
        if (moLocality == null) {
            jtfLocalityCode.setText("");
            jtfLocalityName.setText("");
        }
        else {
            jtfLocalityCode.setText(moLocality.Code);
            jtfLocalityCode.setCaretPosition(0);
            jtfLocalityName.setText(moLocality.Name);
            jtfLocalityName.setCaretPosition(0);
        }
    }
    
    private void setZipCode(final String zipCode) {
        msZipCode = zipCode;
        
        if (msZipCode == null || msZipCode.isEmpty()) {
            jtfZipCode.setText("");
        }
        else {
            jtfZipCode.setText(msZipCode);
            jtfZipCode.setCaretPosition(0);
        }
    }
    
    @Override
    public void setValue(final int type, final Object value) {
        switch (type) {
            case DLadCatalogConsts.ADDRESS_COUNTRY:
                setCountry((DLadCatalogAddressCountry) value);
                break;
            case DLadCatalogConsts.ADDRESS_STATE:
                setState((DLadCatalogAddressState) value);
                break;
            case DLadCatalogConsts.ADDRESS_COUNTY:
                setCounty((DLadCatalogAddressCounty) value);
                break;
            case DLadCatalogConsts.ADDRESS_LOCALITY:
                setLocality((DLadCatalogAddressLocality) value);
                break;
            case DLadCatalogConsts.ADDRESS_ZIP_CODE:
                setZipCode((String) value);
                break;
            default:
                // nothing
        }
    }

    @Override
    public Object getValue(final int type) {
        Object value = null;
        
        switch (type) {
            case DLadCatalogConsts.ADDRESS_DISTRICT:
                value = moGridOptions.getSelectedGridRow();
                break;
            default:
                // nothing
        }
        
        return value;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();
            
            if (button == jbClear) {
                actionPerformedClear();
            }
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getSource() instanceof DBeanFieldText) {
            DBeanFieldText field = (DBeanFieldText) e.getSource();
            
            if (field == moTextDistrictCode) {
                keyPressedDistrictCode(e);
            }
        }
        else if (e.getSource() instanceof JTable) {
            JTable table = (JTable) e.getSource();
            
            if (table == moGridOptions.getTable()) {
                keyPressedTable(e);
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getSource() instanceof DBeanFieldText) {
            DBeanFieldText field = (DBeanFieldText) e.getSource();
            
            if (field == moTextDistrictName || field == moTextDistrictCode) {
                keyReleasedDistrictNameCode(e);
            }
        }
    }
}
