/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sba.mod.lad.form;

import cfd.ver40.DCfdi40Catalogs;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JTable;
import sba.gui.cat.DXmlCatalog;
import sba.gui.cat.DXmlCatalogEntry;
import sba.lib.DLibUtils;
import sba.lib.db.DDbRegistry;
import sba.lib.grid.DGridColumnForm;
import sba.lib.grid.DGridConsts;
import sba.lib.grid.DGridPaneForm;
import sba.lib.grid.DGridRow;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanFieldText;
import sba.lib.gui.bean.DBeanFormDialog;
import sba.mod.lad.db.DLadCatalogAddressCountry;
import sba.mod.lad.db.DLadCatalogAddressCounty;
import sba.mod.lad.db.DLadCatalogAddressState;
import sba.mod.lad.db.DLadCatalogConsts;

/**
 *
 * @author Sergio Flores
 */
public class DPickerCatalogAddressCounty extends DBeanFormDialog implements ActionListener, KeyListener {
    
    protected DLadCatalogAddressCountry moCountry;
    protected DLadCatalogAddressState moState;
    protected DLadCatalogAddressState moOldState;
    protected DGridPaneForm moGridOptions;
    protected ArrayList<DGridRow> maGridRows;

    /**
     * Creates new form DPickerAddressCounty
     */
    public DPickerCatalogAddressCounty(DGuiClient client) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, 0, 0, "Buscar municipio");
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpParams = new javax.swing.JPanel();
        jpParams1 = new javax.swing.JPanel();
        jlCountry = new javax.swing.JLabel();
        jtfCountryCode = new javax.swing.JTextField();
        jtfCountryName = new javax.swing.JTextField();
        jpParams2 = new javax.swing.JPanel();
        jlState = new javax.swing.JLabel();
        jtfStateCode = new javax.swing.JTextField();
        jtfStateName = new javax.swing.JTextField();
        jpParams3 = new javax.swing.JPanel();
        jlCountry1 = new javax.swing.JLabel();
        moTextCountyName = new sba.lib.gui.bean.DBeanFieldText();
        moTextCountyCode = new sba.lib.gui.bean.DBeanFieldText();
        jbClear = new javax.swing.JButton();
        jpOptions = new javax.swing.JPanel();

        jpParams.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros de búsqueda:"));
        jpParams.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        jpParams1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCountry.setText("País:");
        jlCountry.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams1.add(jlCountry);

        jtfCountryCode.setEditable(false);
        jtfCountryCode.setText("TEXT");
        jtfCountryCode.setFocusable(false);
        jtfCountryCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams1.add(jtfCountryCode);

        jtfCountryName.setEditable(false);
        jtfCountryName.setText("TEXT");
        jtfCountryName.setFocusable(false);
        jtfCountryName.setPreferredSize(new java.awt.Dimension(400, 23));
        jpParams1.add(jtfCountryName);

        jpParams.add(jpParams1);

        jpParams2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlState.setText("Estado:");
        jlState.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams2.add(jlState);

        jtfStateCode.setEditable(false);
        jtfStateCode.setText("TEXT");
        jtfStateCode.setFocusable(false);
        jtfStateCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams2.add(jtfStateCode);

        jtfStateName.setEditable(false);
        jtfStateName.setText("TEXT");
        jtfStateName.setFocusable(false);
        jtfStateName.setPreferredSize(new java.awt.Dimension(400, 23));
        jpParams2.add(jtfStateName);

        jpParams.add(jpParams2);

        jpParams3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCountry1.setText("Municipio:");
        jlCountry1.setPreferredSize(new java.awt.Dimension(75, 23));
        jpParams3.add(jlCountry1);

        moTextCountyName.setText("TEXT");
        moTextCountyName.setPreferredSize(new java.awt.Dimension(400, 23));
        jpParams3.add(moTextCountyName);

        moTextCountyCode.setText("TEXT");
        moTextCountyCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jpParams3.add(moTextCountyCode);

        jbClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/gui/img/cmd_std_delete.gif"))); // NOI18N
        jbClear.setToolTipText("Limpiar");
        jbClear.setPreferredSize(new java.awt.Dimension(23, 23));
        jpParams3.add(jbClear);

        jpParams.add(jpParams3);

        getContentPane().add(jpParams, java.awt.BorderLayout.NORTH);

        jpOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones:"));
        jpOptions.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jpOptions, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClear;
    private javax.swing.JLabel jlCountry;
    private javax.swing.JLabel jlCountry1;
    private javax.swing.JLabel jlState;
    private javax.swing.JPanel jpOptions;
    private javax.swing.JPanel jpParams;
    private javax.swing.JPanel jpParams1;
    private javax.swing.JPanel jpParams2;
    private javax.swing.JPanel jpParams3;
    private javax.swing.JTextField jtfCountryCode;
    private javax.swing.JTextField jtfCountryName;
    private javax.swing.JTextField jtfStateCode;
    private javax.swing.JTextField jtfStateName;
    private sba.lib.gui.bean.DBeanFieldText moTextCountyCode;
    private sba.lib.gui.bean.DBeanFieldText moTextCountyName;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        DGuiUtils.setWindowBounds(this, 640, 400);
        
        moTextCountyName.setTextSettings(DGuiUtils.getLabelName(jlState), 100);
        moTextCountyName.setTextCaseType(0);
        moTextCountyCode.setTextSettings(DGuiUtils.getLabelName(jlState), DFormBolUtils.DEF_CODE_ADDRESS_COUNTY.length());
        moTextCountyCode.setTextCaseType(0);
        
        moFields.addField(moTextCountyName);
        moFields.addField(moTextCountyCode);
        moFields.setFormButton(jbSave);
        
        moGridOptions = new DGridPaneForm(miClient, mnFormType, mnFormSubtype, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[2];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT, "Descripción", 400);
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT, "Clave", 100);

                for (DGridColumnForm column : columns) {
                    moModel.getGridColumns().add(column);
                }
            }
        };
        
        jpOptions.add(moGridOptions, BorderLayout.CENTER);
    }
    
    private void populateGridOptions(final Vector<DGridRow> rows) {
        moGridOptions.populateGrid(rows);
        moGridOptions.getTable().addKeyListener(this);
        moGridOptions.getTable().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    actionSave();
                }
            }
        });
    }
    
    private void actionPerformedClear() {
        moTextCountyName.resetField();
        moTextCountyCode.resetField();
        
        moTextCountyName.requestFocus();
    }

    private void keyPressedCountyCode(final KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.VK_ENTER) {
            event.consume();
            moGridOptions.getTable().requestFocusInWindow();
        }
    }
    
    private void keyPressedTable(final KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.VK_ENTER && moGridOptions.getSelectedGridRow() != null) {
            event.consume();
            actionSave();
        }
    }

    private void keyReleasedCountyNameCode(final KeyEvent e) {
        String name = moTextCountyName.getValue().toUpperCase();
        String code = moTextCountyCode.getValue().toUpperCase();
        Vector<DGridRow> rows = new Vector<>();
        
        if (name.isEmpty() && code.isEmpty()) {
            rows.addAll(maGridRows);
        }
        else {
            for (DGridRow row : maGridRows) {
                if ((!name.isEmpty() && row.getRowName().toUpperCase().contains(name)) || (!code.isEmpty() && row.getRowCode().toUpperCase().contains(code))) {
                    rows.add(row);
                }
            }
        }
        
        populateGridOptions(rows);
    }
    
    @Override
    public void resetForm() {
        mnFormResult = 0;
        mbFirstActivation = true;
        
        removeAllListeners();
        
        moFields.resetFields();
        
        try {
            miClient.getFrame().getRootPane().setCursor(new Cursor(Cursor.WAIT_CURSOR));
            
            if (moOldState == null || !moOldState.Code.equals(moState.Code)) {
                moOldState = moState.clone();
                
                maGridRows = new ArrayList<>();
                DXmlCatalog xmlCatalog = DFormBolUtils.getXmlCatalog(DCfdi40Catalogs.XML_CCP_MUN, DFormBolUtils.ATT_STATE, "", null);
                for (DXmlCatalogEntry entry : xmlCatalog.getEntries()) {
                    if (entry.getBelongingCode().equals(moState.Code)) {
                        maGridRows.add(new DLadCatalogAddressCounty(entry.getCode(), entry.getName()));
                    }
                }
                
                if (maGridRows.isEmpty()) {
                    miClient.showMsgBoxWarning("No se encontraron municipios para el estado '" + moState.Code + "'.");
                }
            }
            
            populateGridOptions(new Vector<>(maGridRows));
        }
        catch (Exception e) {
            DLibUtils.showException(this, e);
        }
        finally {
            miClient.getFrame().getRootPane().setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
        
        addAllListeners();
    }
    
    @Override
    public void addAllListeners() {
        jbClear.addActionListener(this);
        moTextCountyName.addKeyListener(this);
        moTextCountyCode.addKeyListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbClear.removeActionListener(this);
        moTextCountyName.removeKeyListener(this);
        moTextCountyCode.removeKeyListener(this);
    }

    @Override
    public void reloadCatalogues() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public DDbRegistry getRegistry() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public DGuiValidation validateForm() {
        DGuiValidation validation = new DGuiValidation();
        
        if (moGridOptions.getSelectedGridRow() == null) {
            validation.setMessage(DGridConsts.MSG_SELECT_ROW);
            validation.setComponent(moGridOptions.getTable());
        }
        
        return validation;
    }
    
    private void setCountry(final DLadCatalogAddressCountry country) {
        moCountry = country;
        
        if (moCountry == null) {
            jtfCountryCode.setText("");
            jtfCountryName.setText("");
        }
        else {
            jtfCountryCode.setText(moCountry.Code);
            jtfCountryCode.setCaretPosition(0);
            jtfCountryName.setText(moCountry.Name);
            jtfCountryName.setCaretPosition(0);
        }
    }
    
    private void setState(final DLadCatalogAddressState state) {
        moState = state;
        
        if (moState == null) {
            jtfStateCode.setText("");
            jtfStateName.setText("");
        }
        else {
            jtfStateCode.setText(moState.Code);
            jtfStateCode.setCaretPosition(0);
            jtfStateName.setText(moState.Name);
            jtfStateName.setCaretPosition(0);
        }
    }
    
    @Override
    public void setValue(final int type, final Object value) {
        switch (type) {
            case DLadCatalogConsts.ADDRESS_COUNTRY:
                setCountry((DLadCatalogAddressCountry) value);
                break;
            case DLadCatalogConsts.ADDRESS_STATE:
                setState((DLadCatalogAddressState) value);
                break;
            default:
                // nothing
        }
    }

    @Override
    public Object getValue(final int type) {
        Object value = null;
        
        switch (type) {
            case DLadCatalogConsts.ADDRESS_COUNTY:
                value = moGridOptions.getSelectedGridRow();
                break;
            default:
                // nothing
        }
        
        return value;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();
            
            if (button == jbClear) {
                actionPerformedClear();
            }
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getSource() instanceof DBeanFieldText) {
            DBeanFieldText field = (DBeanFieldText) e.getSource();
            
            if (field == moTextCountyCode) {
                keyPressedCountyCode(e);
            }
        }
        else if (e.getSource() instanceof JTable) {
            JTable table = (JTable) e.getSource();
            
            if (table == moGridOptions.getTable()) {
                keyPressedTable(e);
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getSource() instanceof DBeanFieldText) {
            DBeanFieldText field = (DBeanFieldText) e.getSource();
            
            if (field == moTextCountyName || field == moTextCountyCode) {
                keyReleasedCountyNameCode(e);
            }
        }
    }
}
