/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DDialogBranchAddress.java
 *
 * Created on 30/10/2011, 02:52:57 PM
 */

package sba.mod.bpr.form;

import sba.lib.DLibConsts;
import sba.lib.db.DDbRegistry;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanFormDialog;
import sba.mod.DModConsts;
import sba.mod.bpr.db.DDbBranchAddress;

/**
 *
 * @author Sergio Flores
 */
public class DDialogBranchAddress extends DBeanFormDialog {

    private DDbBranchAddress moRegistry;

    /** Creates new form DDialogBranchAddress */
    public DDialogBranchAddress(DGuiClient client) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, DModConsts.BU_ADD, DLibConsts.UNDEFINED, "Domicilio");
        initComponents();
        initComponentsCustom();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        moPanelBranchAddress = new sba.mod.bpr.form.DPanelBranchAddress();

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel.setLayout(new java.awt.BorderLayout());
        jPanel.add(moPanelBranchAddress, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsCustom() {
        DGuiUtils.setWindowBounds(this, 900, 400);

        moPanelBranchAddress.setPanelSettings(miClient);
        moPanelBranchAddress.getFields().setFormButton(jbSave);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    private sba.mod.bpr.form.DPanelBranchAddress moPanelBranchAddress;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addAllListeners() {

    }

    @Override
    public void removeAllListeners() {

    }

    @Override
    public void reloadCatalogues() {

    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        moRegistry = (DDbBranchAddress) registry;

        mnFormResult = DLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) { } else { }

        moPanelBranchAddress.setRegistry(registry);

        addAllListeners();
    }

    @Override
    public DDbBranchAddress getRegistry() throws Exception {
        DDbBranchAddress registry = moPanelBranchAddress.getRegistry();

        if (registry.isRegistryNew()) { }

        return registry;
    }

    @Override
    public DGuiValidation validateForm() {
        DGuiValidation validation = moPanelBranchAddress.validatePanel();

        return validation;
    }
}
