/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DFormBizPartner.java
 *
 * Created on 1/10/2011, 03:24:00 PM
 */

package sba.mod.bpr.form;

import cfd.DCfdConsts;
import cfd.ver40.DCfdi40Catalogs;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import sba.gui.DGuiClientApp;
import sba.gui.cat.DXmlCatalog;
import sba.lib.DLibConsts;
import sba.lib.DLibTimeUtils;
import sba.lib.DLibUtils;
import sba.lib.db.DDbRegistry;
import sba.lib.grid.DGridColumnForm;
import sba.lib.grid.DGridConsts;
import sba.lib.grid.DGridPaneForm;
import sba.lib.grid.DGridRow;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanFieldBoolean;
import sba.lib.gui.bean.DBeanFieldKey;
import sba.lib.gui.bean.DBeanFieldText;
import sba.lib.gui.bean.DBeanForm;
import sba.mod.DModConsts;
import sba.mod.DModSysConsts;
import sba.mod.bpr.db.DDbBizPartner;
import sba.mod.bpr.db.DDbBizPartnerConfig;
import sba.mod.bpr.db.DDbBizPartnerType;
import sba.mod.bpr.db.DDbBranch;
import sba.mod.bpr.db.DDbBranchAddress;
import sba.mod.cfg.db.DDbConfigCompany;
import sba.mod.mkt.db.DDbAgentConfig;

/**
 *
 * @author Sergio Flores
 */
public class DFormBizPartner extends DBeanForm implements ActionListener, ItemListener, FocusListener {

    private int mnBizPartnerClass;
    private DDbBizPartner moRegistry;
    private DGridPaneForm moGridBranchAddresses;
    private DXmlCatalog moXmlCatalogCfdUsage;

    /** Creates new form DFormBizPartner */
    public DFormBizPartner(DGuiClient client, int subtype, String title) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, DModConsts.BU_BPR, subtype, title);
        mnBizPartnerClass = mnFormSubtype;
        initComponents();
        initComponentsCustom();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNamePrintingPolicy = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jpRegistry = new javax.swing.JPanel();
        jpRegistry1 = new javax.swing.JPanel();
        jpRegistry11 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        moTextCode = new sba.lib.gui.bean.DBeanFieldText();
        moKeyIdentityType = new sba.lib.gui.bean.DBeanFieldKey();
        jbIdentityType = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jlLastname = new javax.swing.JLabel();
        moTextLastname = new sba.lib.gui.bean.DBeanFieldText();
        jPanel9 = new javax.swing.JPanel();
        jlFirstname = new javax.swing.JLabel();
        moTextFirstname = new sba.lib.gui.bean.DBeanFieldText();
        jPanel8 = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        moTextName = new sba.lib.gui.bean.DBeanFieldText();
        jlNameHelp = new javax.swing.JLabel();
        jlNameSeparator = new javax.swing.JLabel();
        moRadNamePrintingPolicyName = new sba.lib.gui.bean.DBeanFieldRadio();
        jPanel13 = new javax.swing.JPanel();
        jlNameFiscal = new javax.swing.JLabel();
        moTextNameFiscal = new sba.lib.gui.bean.DBeanFieldText();
        moTextNameCapitalRegime = new sba.lib.gui.bean.DBeanFieldText();
        jlNameFiscalHellp = new javax.swing.JLabel();
        jtbNameFiscalCustomized = new javax.swing.JToggleButton();
        moRadNamePrintingPolicyNameFiscal = new sba.lib.gui.bean.DBeanFieldRadio();
        jPanel11 = new javax.swing.JPanel();
        jlNickname = new javax.swing.JLabel();
        moTextNickname = new sba.lib.gui.bean.DBeanFieldText();
        jPanel10 = new javax.swing.JPanel();
        jlFiscalId = new javax.swing.JLabel();
        moTextFiscalId = new sba.lib.gui.bean.DBeanFieldText();
        jbSetDefaultFiscalId = new javax.swing.JButton();
        moBoolFiscalHomologous = new sba.lib.gui.bean.DBeanFieldBoolean();
        jlFiscalId1 = new javax.swing.JLabel();
        moTextAlternativeId = new sba.lib.gui.bean.DBeanFieldText();
        jPanel12 = new javax.swing.JPanel();
        jlNote = new javax.swing.JLabel();
        moTextNote = new sba.lib.gui.bean.DBeanFieldText();
        jpRegistry12 = new javax.swing.JPanel();
        moPanelBranch = new sba.mod.bpr.form.DPanelBranch();
        jpRegistry2 = new javax.swing.JPanel();
        moPanelBranchAddress = new sba.mod.bpr.form.DPanelBranchAddress();
        jpConfig = new javax.swing.JPanel();
        jpConfig1 = new javax.swing.JPanel();
        jpConfig11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jlBizPartnerType = new javax.swing.JLabel();
        moKeyBizPartnerType = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel21 = new javax.swing.JPanel();
        jlDateStart = new javax.swing.JLabel();
        moDateStart = new sba.lib.gui.bean.DBeanFieldDate();
        jPanel22 = new javax.swing.JPanel();
        jlDateEnd = new javax.swing.JLabel();
        moDateEnd = new sba.lib.gui.bean.DBeanFieldDate();
        jPanel20 = new javax.swing.JPanel();
        jlCodeOwn = new javax.swing.JLabel();
        moTextCodeOwn = new sba.lib.gui.bean.DBeanFieldText();
        jlCodeOwnInfo = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jlForeignId = new javax.swing.JLabel();
        moTextForeignId = new sba.lib.gui.bean.DBeanFieldText();
        jlForeignIdInfo = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        moBoolAgent = new sba.lib.gui.bean.DBeanFieldBoolean();
        moBoolBank = new sba.lib.gui.bean.DBeanFieldBoolean();
        moBoolCarrier = new sba.lib.gui.bean.DBeanFieldBoolean();
        jPanel34 = new javax.swing.JPanel();
        jlAgentType = new javax.swing.JLabel();
        moKeyAgentType = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel23 = new javax.swing.JPanel();
        jlEmissionType = new javax.swing.JLabel();
        moKeyEmissionType = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel36 = new javax.swing.JPanel();
        jlXmlAddendaType = new javax.swing.JLabel();
        moKeyXmlAddendaType = new sba.lib.gui.bean.DBeanFieldKey();
        jbXmlAddendaType = new javax.swing.JButton();
        jPanel38 = new javax.swing.JPanel();
        jlTaxRegime = new javax.swing.JLabel();
        moKeyTaxRegime = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel2 = new javax.swing.JPanel();
        jlAddressFiscal = new javax.swing.JLabel();
        moTextAddressFiscal = new sba.lib.gui.bean.DBeanFieldText();
        jlAddressFiscalInfo = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jlWeb = new javax.swing.JLabel();
        moTextWeb = new sba.lib.gui.bean.DBeanFieldText();
        jpConfig12 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jlCurrency = new javax.swing.JLabel();
        moKeyCurrency = new sba.lib.gui.bean.DBeanFieldKey();
        jbCurrency = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        moBoolCreditByUser = new sba.lib.gui.bean.DBeanFieldBoolean();
        jPanel27 = new javax.swing.JPanel();
        jlCreditType = new javax.swing.JLabel();
        moKeyCreditType = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel28 = new javax.swing.JPanel();
        jlCreditLimit = new javax.swing.JLabel();
        moCurCreditLimit = new sba.lib.gui.bean.DBeanCompoundFieldCurrency();
        jPanel29 = new javax.swing.JPanel();
        jlCreditDays = new javax.swing.JLabel();
        moIntCreditDays = new sba.lib.gui.bean.DBeanFieldInteger();
        jPanel30 = new javax.swing.JPanel();
        jlCreditDaysGrace = new javax.swing.JLabel();
        moIntCreditDaysGrace = new sba.lib.gui.bean.DBeanFieldInteger();
        jPanel35 = new javax.swing.JPanel();
        jlModeOfPaymentType = new javax.swing.JLabel();
        moKeyModeOfPaymentType = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel37 = new javax.swing.JPanel();
        jlCfdUsage = new javax.swing.JLabel();
        moKeyCfdUsage = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel1 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        moBoolAbpBizPartnerByUser = new sba.lib.gui.bean.DBeanFieldBoolean();
        jPanel31 = new javax.swing.JPanel();
        jlAbpBizPartner = new javax.swing.JLabel();
        moKeyAbpBizPartner = new sba.lib.gui.bean.DBeanFieldKey();
        jpConfig2 = new javax.swing.JPanel();

        jpRegistry.setLayout(new java.awt.BorderLayout());

        jpRegistry1.setLayout(new java.awt.BorderLayout());

        jpRegistry11.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel5.setLayout(new java.awt.GridLayout(8, 1, 0, 5));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCode.setText("Código:*");
        jlCode.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel6.add(jlCode);

        moTextCode.setPreferredSize(new java.awt.Dimension(110, 23));
        jPanel6.add(moTextCode);

        moKeyIdentityType.setToolTipText("Tipo persona");
        moKeyIdentityType.setPreferredSize(new java.awt.Dimension(152, 23));
        jPanel6.add(moKeyIdentityType);

        jbIdentityType.setText("<");
        jbIdentityType.setToolTipText("Modificar tipo persona");
        jbIdentityType.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jbIdentityType.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel6.add(jbIdentityType);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlLastname.setText("Apellido(s):*");
        jlLastname.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel7.add(jlLastname);

        moTextLastname.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel7.add(moTextLastname);

        jPanel5.add(jPanel7);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlFirstname.setText("Nombre(s):*");
        jlFirstname.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel9.add(jlFirstname);

        moTextFirstname.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel9.add(moTextFirstname);

        jPanel5.add(jPanel9);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlName.setText("Nombre:*");
        jlName.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel8.add(jlName);

        moTextName.setToolTipText("Nombre completo");
        moTextName.setPreferredSize(new java.awt.Dimension(320, 23));
        jPanel8.add(moTextName);

        jlNameHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/gui/img/icon_help.png"))); // NOI18N
        jlNameHelp.setToolTipText("Nombre completo (para usarse en el sistema)");
        jlNameHelp.setPreferredSize(new java.awt.Dimension(15, 23));
        jPanel8.add(jlNameHelp);

        jlNameSeparator.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel8.add(jlNameSeparator);

        bgNamePrintingPolicy.add(moRadNamePrintingPolicyName);
        moRadNamePrintingPolicyName.setText("Para imprimir");
        moRadNamePrintingPolicyName.setToolTipText("Imprimir nombre completo en documentos");
        moRadNamePrintingPolicyName.setPreferredSize(new java.awt.Dimension(95, 23));
        jPanel8.add(moRadNamePrintingPolicyName);

        jPanel5.add(jPanel8);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlNameFiscal.setText("Razón social:*");
        jlNameFiscal.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel13.add(jlNameFiscal);

        moTextNameFiscal.setToolTipText("Razón social o denominación");
        moTextNameFiscal.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel13.add(moTextNameFiscal);

        moTextNameCapitalRegime.setToolTipText("Régimen de capital (opcional)");
        moTextNameCapitalRegime.setPreferredSize(new java.awt.Dimension(65, 23));
        jPanel13.add(moTextNameCapitalRegime);

        jlNameFiscalHellp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/gui/img/icon_help.png"))); // NOI18N
        jlNameFiscalHellp.setToolTipText("Razón social o denominación (para usarse en el CFDI)");
        jlNameFiscalHellp.setPreferredSize(new java.awt.Dimension(15, 23));
        jPanel13.add(jlNameFiscalHellp);

        jtbNameFiscalCustomized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/gui/img/cmd_std_edit_off.gif"))); // NOI18N
        jtbNameFiscalCustomized.setToolTipText("Personalizar razón social o denominación");
        jtbNameFiscalCustomized.setPreferredSize(new java.awt.Dimension(23, 23));
        jtbNameFiscalCustomized.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/gui/img/cmd_std_edit.gif"))); // NOI18N
        jPanel13.add(jtbNameFiscalCustomized);

        bgNamePrintingPolicy.add(moRadNamePrintingPolicyNameFiscal);
        moRadNamePrintingPolicyNameFiscal.setText("Para imprimir");
        moRadNamePrintingPolicyNameFiscal.setToolTipText("Imprimir razón social o denominación en documentos");
        moRadNamePrintingPolicyNameFiscal.setPreferredSize(new java.awt.Dimension(95, 23));
        jPanel13.add(moRadNamePrintingPolicyNameFiscal);

        jPanel5.add(jPanel13);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlNickname.setText("Alias:");
        jlNickname.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel11.add(jlNickname);

        moTextNickname.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel11.add(moTextNickname);

        jPanel5.add(jPanel11);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlFiscalId.setText("RFC:*");
        jlFiscalId.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel10.add(jlFiscalId);

        moTextFiscalId.setPreferredSize(new java.awt.Dimension(110, 23));
        jPanel10.add(moTextFiscalId);

        jbSetDefaultFiscalId.setText("<");
        jbSetDefaultFiscalId.setToolTipText("Poner RFC predeterminado");
        jbSetDefaultFiscalId.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jbSetDefaultFiscalId.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel10.add(jbSetDefaultFiscalId);

        moBoolFiscalHomologous.setText("Es homólogo");
        moBoolFiscalHomologous.setToolTipText("El RFC lo comparten varios contribuyentes");
        jPanel10.add(moBoolFiscalHomologous);

        jlFiscalId1.setText("CURP:");
        jlFiscalId1.setPreferredSize(new java.awt.Dimension(40, 23));
        jPanel10.add(jlFiscalId1);

        moTextAlternativeId.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel10.add(moTextAlternativeId);

        jPanel5.add(jPanel10);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlNote.setText("Notas:");
        jlNote.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel12.add(jlNote);

        moTextNote.setPreferredSize(new java.awt.Dimension(350, 23));
        jPanel12.add(moTextNote);

        jPanel5.add(jPanel12);

        jpRegistry11.add(jPanel5, java.awt.BorderLayout.NORTH);

        jpRegistry1.add(jpRegistry11, java.awt.BorderLayout.WEST);

        jpRegistry12.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la matriz:"));
        jpRegistry12.setLayout(new java.awt.BorderLayout());
        jpRegistry12.add(moPanelBranch, java.awt.BorderLayout.CENTER);

        jpRegistry1.add(jpRegistry12, java.awt.BorderLayout.CENTER);

        jpRegistry.add(jpRegistry1, java.awt.BorderLayout.NORTH);

        jpRegistry2.setLayout(new java.awt.BorderLayout());
        jpRegistry2.add(moPanelBranchAddress, java.awt.BorderLayout.CENTER);

        jpRegistry.add(jpRegistry2, java.awt.BorderLayout.CENTER);

        jTabbedPane.addTab("Registro", jpRegistry);

        jpConfig.setLayout(new java.awt.BorderLayout());

        jpConfig1.setLayout(new java.awt.BorderLayout());

        jpConfig11.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo:"));
        jpConfig11.setLayout(new java.awt.GridLayout(12, 1, 0, 5));

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlBizPartnerType.setText("Tipo:*");
        jlBizPartnerType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel18.add(jlBizPartnerType);

        moKeyBizPartnerType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel18.add(moKeyBizPartnerType);

        jpConfig11.add(jPanel18);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDateStart.setText("Inicio relación:*");
        jlDateStart.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel21.add(jlDateStart);
        jPanel21.add(moDateStart);

        jpConfig11.add(jPanel21);

        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDateEnd.setText("Término relación:");
        jlDateEnd.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel22.add(jlDateEnd);
        jPanel22.add(moDateEnd);

        jpConfig11.add(jPanel22);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCodeOwn.setText("Código propio:");
        jlCodeOwn.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel20.add(jlCodeOwn);
        jPanel20.add(moTextCodeOwn);

        jlCodeOwnInfo.setForeground(java.awt.Color.gray);
        jlCodeOwnInfo.setText("(Código de empresa otorgado a nosotros.)");
        jlCodeOwnInfo.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel20.add(jlCodeOwnInfo);

        jpConfig11.add(jPanel20);

        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlForeignId.setText("ID fiscal:");
        jlForeignId.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel24.add(jlForeignId);
        jPanel24.add(moTextForeignId);

        jlForeignIdInfo.setForeground(java.awt.Color.gray);
        jlForeignIdInfo.setText("(ID fiscal en el país de origen.)");
        jlForeignIdInfo.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel24.add(jlForeignIdInfo);

        jpConfig11.add(jPanel24);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        moBoolAgent.setText("Agente");
        jPanel19.add(moBoolAgent);

        moBoolBank.setText("Banco");
        jPanel19.add(moBoolBank);

        moBoolCarrier.setText("Transportista");
        jPanel19.add(moBoolCarrier);

        jpConfig11.add(jPanel19);

        jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlAgentType.setText("Tipo agente:*");
        jlAgentType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel34.add(jlAgentType);

        moKeyAgentType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel34.add(moKeyAgentType);

        jpConfig11.add(jPanel34);

        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlEmissionType.setText("Tipo emisión:*");
        jlEmissionType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel23.add(jlEmissionType);

        moKeyEmissionType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel23.add(moKeyEmissionType);

        jpConfig11.add(jPanel23);

        jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlXmlAddendaType.setText("Tipo addenda:*");
        jlXmlAddendaType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel36.add(jlXmlAddendaType);

        moKeyXmlAddendaType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel36.add(moKeyXmlAddendaType);

        jbXmlAddendaType.setText("<");
        jbXmlAddendaType.setToolTipText("Modificar tipo addenda");
        jbXmlAddendaType.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jbXmlAddendaType.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel36.add(jbXmlAddendaType);

        jpConfig11.add(jPanel36);

        jPanel38.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTaxRegime.setText("Régimen fiscal:*");
        jlTaxRegime.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel38.add(jlTaxRegime);

        moKeyTaxRegime.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel38.add(moKeyTaxRegime);

        jpConfig11.add(jPanel38);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlAddressFiscal.setText("Domicilio fiscal:");
        jlAddressFiscal.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(jlAddressFiscal);
        jPanel2.add(moTextAddressFiscal);

        jlAddressFiscalInfo.setForeground(java.awt.Color.gray);
        jlAddressFiscalInfo.setText("(Código postal del domicilio fiscal. Dato opcional.)");
        jlAddressFiscalInfo.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel2.add(jlAddressFiscalInfo);

        jpConfig11.add(jPanel2);

        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeb.setForeground(new java.awt.Color(0, 102, 102));
        jlWeb.setText("Sitio web:");
        jlWeb.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel25.add(jlWeb);

        moTextWeb.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel25.add(moTextWeb);

        jpConfig11.add(jPanel25);

        jpConfig1.add(jpConfig11, java.awt.BorderLayout.WEST);

        jpConfig12.setBorder(javax.swing.BorderFactory.createTitledBorder("Crédito:"));
        jpConfig12.setLayout(new java.awt.GridLayout(12, 1, 0, 5));

        jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCurrency.setText("Moneda default:");
        jlCurrency.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel32.add(jlCurrency);

        moKeyCurrency.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel32.add(moKeyCurrency);

        jbCurrency.setText("<");
        jbCurrency.setToolTipText("Modificar moneda default");
        jbCurrency.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jbCurrency.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel32.add(jbCurrency);

        jpConfig12.add(jPanel32);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        jpConfig12.add(jPanel3);

        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        moBoolCreditByUser.setText("Configuración manual de crédito");
        moBoolCreditByUser.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel26.add(moBoolCreditByUser);

        jpConfig12.add(jPanel26);

        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCreditType.setText("Tipo crédito:*");
        jlCreditType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel27.add(jlCreditType);

        moKeyCreditType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel27.add(moKeyCreditType);

        jpConfig12.add(jPanel27);

        jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCreditLimit.setText("Límite crédito:*");
        jlCreditLimit.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel28.add(jlCreditLimit);
        jPanel28.add(moCurCreditLimit);

        jpConfig12.add(jPanel28);

        jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCreditDays.setText("Días crédito:*");
        jlCreditDays.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel29.add(jlCreditDays);

        moIntCreditDays.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel29.add(moIntCreditDays);

        jpConfig12.add(jPanel29);

        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCreditDaysGrace.setText("Días gracia:");
        jlCreditDaysGrace.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel30.add(jlCreditDaysGrace);

        moIntCreditDaysGrace.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel30.add(moIntCreditDaysGrace);

        jpConfig12.add(jPanel30);

        jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlModeOfPaymentType.setText("Tipo forma pago:");
        jlModeOfPaymentType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel35.add(jlModeOfPaymentType);

        moKeyModeOfPaymentType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel35.add(moKeyModeOfPaymentType);

        jpConfig12.add(jPanel35);

        jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCfdUsage.setText("Uso CFDI:");
        jlCfdUsage.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel37.add(jlCfdUsage);

        moKeyCfdUsage.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel37.add(moKeyCfdUsage);

        jpConfig12.add(jPanel37);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        jpConfig12.add(jPanel1);

        jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        moBoolAbpBizPartnerByUser.setText("Configuración manual de paquete contable");
        moBoolAbpBizPartnerByUser.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel33.add(moBoolAbpBizPartnerByUser);

        jpConfig12.add(jPanel33);

        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlAbpBizPartner.setText("Paquete contable:*");
        jlAbpBizPartner.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel31.add(jlAbpBizPartner);

        moKeyAbpBizPartner.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel31.add(moKeyAbpBizPartner);

        jpConfig12.add(jPanel31);

        jpConfig1.add(jpConfig12, java.awt.BorderLayout.CENTER);

        jpConfig.add(jpConfig1, java.awt.BorderLayout.PAGE_START);

        jpConfig2.setBorder(javax.swing.BorderFactory.createTitledBorder("Otros domicilios:"));
        jpConfig2.setLayout(new java.awt.BorderLayout());
        jpConfig.add(jpConfig2, java.awt.BorderLayout.CENTER);

        jTabbedPane.addTab("Configuración", jpConfig);

        getContentPane().add(jTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsCustom() {
        int lenCode = ((DDbConfigCompany) miClient.getSession().getConfigCompany()).getLengthCodeBizPartner();

        DGuiUtils.setWindowBounds(this, 960, 600);

        moTextCode.setTextSettings(DGuiUtils.getLabelName(jlCode), lenCode == 0 || lenCode > 15 ? 15 : lenCode);
        moKeyIdentityType.setKeySettings(miClient, moKeyIdentityType.getToolTipText(), true);
        moTextLastname.setTextSettings(DGuiUtils.getLabelName(jlLastname), 99);
        moTextFirstname.setTextSettings(DGuiUtils.getLabelName(jlFirstname), 99);
        moTextName.setTextSettings(DGuiUtils.getLabelName(jlName), 200);
        moTextNameFiscal.setTextSettings(DGuiUtils.getLabelName(jlNameFiscal), 200);
        moTextNameCapitalRegime.setTextSettings(DGuiUtils.getLabelName(jlNameFiscal) + ": " + moTextNameCapitalRegime.getToolTipText(), 50, 0);
        moRadNamePrintingPolicyName.setBooleanSettings(moRadNamePrintingPolicyName.getText() + " " + moTextName.getFieldName(), false);
        moRadNamePrintingPolicyNameFiscal.setBooleanSettings(moRadNamePrintingPolicyNameFiscal.getText() + " " + moTextNameFiscal.getFieldName(), false);
        moTextNickname.setTextSettings(DGuiUtils.getLabelName(jlNickname), 100, 0);
        moTextFiscalId.setTextSettings(DGuiUtils.getLabelName(jlFiscalId), 20);
        moBoolFiscalHomologous.setBooleanSettings(moBoolFiscalHomologous.getText(), false);
        moTextAlternativeId.setTextSettings(moTextAlternativeId.getToolTipText(), 25, 0);
        moTextNote.setTextSettings(DGuiUtils.getLabelName(jlNote), 100, 0);
        moKeyBizPartnerType.setKeySettings(miClient, DGuiUtils.getLabelName(jlBizPartnerType), true);
        moDateStart.setDateSettings(miClient, DGuiUtils.getLabelName(jlDateStart), true);
        moDateEnd.setDateSettings(miClient, DGuiUtils.getLabelName(jlDateEnd), false);
        moTextCodeOwn.setTextSettings(DGuiUtils.getLabelName(jlCodeOwn), 15, 0);
        moTextForeignId.setTextSettings(DGuiUtils.getLabelName(jlForeignId), 15, 0);
        moBoolAgent.setBooleanSettings(moBoolAgent.getText(), false);
        moBoolBank.setBooleanSettings(moBoolBank.getText(), false);
        moBoolCarrier.setBooleanSettings(moBoolCarrier.getText(), false);
        moKeyAgentType.setKeySettings(miClient, DGuiUtils.getLabelName(jlAgentType), true);
        moKeyEmissionType.setKeySettings(miClient, DGuiUtils.getLabelName(jlEmissionType), true);
        moKeyXmlAddendaType.setKeySettings(miClient, DGuiUtils.getLabelName(jlXmlAddendaType), true);
        moKeyTaxRegime.setKeySettings(miClient, DGuiUtils.getLabelName(jlTaxRegime), true);
        moTextAddressFiscal.setTextSettings(DGuiUtils.getLabelName(jlAddressFiscal), 5, 0);
        moTextWeb.setTextSettings(DGuiUtils.getLabelName(jlWeb), 50, 0);
        moTextWeb.setTextCaseType(0);
        moKeyCurrency.setKeySettings(miClient, DGuiUtils.getLabelName(jlCurrency), false);
        moBoolCreditByUser.setBooleanSettings(moBoolCreditByUser.getText(), false);
        moKeyCreditType.setKeySettings(miClient, DGuiUtils.getLabelName(jlCreditType), true);
        moCurCreditLimit.setCompoundFieldSettings(miClient);
        moCurCreditLimit.getField().setDecimalSettings(DGuiUtils.getLabelName(jlCreditLimit), DGuiConsts.GUI_TYPE_DEC_AMT, true);
        moIntCreditDays.setIntegerSettings(DGuiUtils.getLabelName(jlCreditDays), DGuiConsts.GUI_TYPE_INT, true);
        moIntCreditDaysGrace.setIntegerSettings(DGuiUtils.getLabelName(jlCreditDaysGrace), DGuiConsts.GUI_TYPE_INT, false);
        moKeyModeOfPaymentType.setKeySettings(miClient, DGuiUtils.getLabelName(jlModeOfPaymentType), false);
        moKeyCfdUsage.setKeySettings(miClient, DGuiUtils.getLabelName(jlCfdUsage), false);
        moBoolAbpBizPartnerByUser.setBooleanSettings(moBoolAbpBizPartnerByUser.getText(), false);
        moKeyAbpBizPartner.setKeySettings(miClient, DGuiUtils.getLabelName(jlAbpBizPartner), true);

        moFields.addField(moTextCode, 0);
        moFields.addField(moKeyIdentityType, 0);
        moFields.addField(moTextLastname, 0);
        moFields.addField(moTextFirstname, 0);
        moFields.addField(moTextName, 0);
        moFields.addField(moTextNameFiscal, 0);
        moFields.addField(moTextNameCapitalRegime, 0);
        moFields.addField(moRadNamePrintingPolicyName, 0);
        moFields.addField(moRadNamePrintingPolicyNameFiscal, 0);
        moFields.addField(moTextNickname, 0);
        moFields.addField(moTextFiscalId, 0);
        moFields.addField(moBoolFiscalHomologous, 0);
        moFields.addField(moTextAlternativeId, 0);
        moFields.addField(moTextNote, 0);
        moFields.addField(moKeyBizPartnerType, 1);
        moFields.addField(moDateStart, 1);
        moFields.addField(moDateEnd, 1);
        moFields.addField(moTextCodeOwn, 1);
        moFields.addField(moTextForeignId, 1);
        moFields.addField(moBoolAgent, 1);
        moFields.addField(moBoolBank, 1);
        moFields.addField(moBoolCarrier, 1);
        moFields.addField(moKeyAgentType, 1);
        moFields.addField(moKeyEmissionType, 1);
        moFields.addField(moKeyXmlAddendaType, 1);
        moFields.addField(moKeyTaxRegime, 1);
        moFields.addField(moTextAddressFiscal, 1);
        moFields.addField(moTextWeb, 1);
        moFields.addField(moKeyCurrency, 1);
        moFields.addField(moBoolCreditByUser, 1);
        moFields.addField(moKeyCreditType, 1);
        moFields.addField(moCurCreditLimit.getField(), 1);
        moFields.addField(moIntCreditDays, 1);
        moFields.addField(moIntCreditDaysGrace, 1);
        moFields.addField(moKeyModeOfPaymentType, 1);
        moFields.addField(moKeyCfdUsage, 1);
        moFields.addField(moBoolAbpBizPartnerByUser, 1);
        moFields.addField(moKeyAbpBizPartner, 1);

        moFields.setFormButton(jbSave);
        moFields.setTabbedPane(jTabbedPane);

        moPanelBranch.setPanelSettings(miClient);
        moPanelBranch.setForHeadquarters(true);
        moPanelBranch.setForCompany(false);
        moPanelBranchAddress.setPanelSettings(miClient);
        moPanelBranchAddress.setHeadquarters(true);

        moTextNote.setNextField(moPanelBranch.getFieldFirst());
        moPanelBranch.getFieldLast().setNextField(moPanelBranchAddress.getFieldFirst());
        moPanelBranchAddress.getFields().setFormButton(jbSave);

        moGridBranchAddresses = new DGridPaneForm(miClient, DModConsts.BU_ADD, mnBizPartnerClass, "Otros domicilios") {

            @Override
            public void initGrid() {

            }

            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[9];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_S, "Nombre");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_M, "Calle");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_S, "Colonia");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_M, "Localidad");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_CAT, "CP");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_BOOL_S, "Default");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_BOOL_S, DGridConsts.COL_TITLE_IS_DIS);
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_BOOL_S, DGridConsts.COL_TITLE_IS_DEL);
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_BOOL_S, DGridConsts.COL_TITLE_IS_SYS);

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };

        moGridBranchAddresses.setForm(new DDialogBranchAddress(miClient));
        jpConfig2.add(moGridBranchAddresses, BorderLayout.CENTER);

        mvFormGrids.add(moGridBranchAddresses);
        
        moXmlCatalogCfdUsage = ((DGuiClientApp) miClient).getXmlCatalogsMap().get(DCfdi40Catalogs.CAT_CFDI_USO);
        moXmlCatalogCfdUsage.populateCatalog(moKeyCfdUsage);
        
        boolean isReceiver = isReceiver();
        
        jlEmissionType.setEnabled(isReceiver);
        jlXmlAddendaType.setEnabled(isReceiver);
        jlTaxRegime.setEnabled(isReceiver);
        jlAddressFiscal.setEnabled(isReceiver);
        
        jlModeOfPaymentType.setEnabled(isReceiver);
        jlCfdUsage.setEnabled(isReceiver);
    }
    
    private boolean isCustomer() {
        return mnBizPartnerClass == DModSysConsts.BS_BPR_CL_CUS;
    }

    private boolean isDebtor() {
        return mnBizPartnerClass == DModSysConsts.BS_BPR_CL_DBR;
    }
    
    private boolean isReceiver() {
        return isCustomer() || isDebtor();
    }

    private void updateStatusFieldsIdentityType() {
        if (moKeyIdentityType.getSelectedIndex() <= 0) {
            // persons:
            moTextLastname.setEditable(false);
            moTextFirstname.setEditable(false);
            moTextAlternativeId.setEditable(false);
            jtbNameFiscalCustomized.setEnabled(false);
            
            // organizations:
            moTextName.setEditable(false);
            moTextNameFiscal.setEditable(false);
            moTextNameCapitalRegime.setEditable(false);
            
            // both entity types:
            moRadNamePrintingPolicyName.setEnabled(false);
            moRadNamePrintingPolicyNameFiscal.setEnabled(false);
            
            moKeyTaxRegime.setEnabled(false);
            moTextAddressFiscal.setEnabled(false);
        }
        else {
            boolean isReceiver = isReceiver();
            boolean isReceiverNameFiscalCustomized = isReceiver && jtbNameFiscalCustomized.isSelected(); // only for persons!
            
            switch (moKeyIdentityType.getValue()[0]) {
                case DModSysConsts.BS_IDY_TP_PER:
                    // persons:
                    moTextLastname.setEditable(true);
                    moTextFirstname.setEditable(true);
                    moTextAlternativeId.setEditable(true);
                    jtbNameFiscalCustomized.setEnabled(isReceiver);
                    
                    // organizations:
                    moTextName.setEditable(false);
                    moTextNameFiscal.setEditable(isReceiverNameFiscalCustomized);
                    moTextNameCapitalRegime.setEditable(false);
                    
                    // both entity types:
                    moRadNamePrintingPolicyName.setEnabled(isReceiverNameFiscalCustomized);
                    moRadNamePrintingPolicyNameFiscal.setEnabled(isReceiverNameFiscalCustomized);
                    break;

                case DModSysConsts.BS_IDY_TP_ORG:
                    // persons:
                    moTextLastname.setEditable(false);
                    moTextFirstname.setEditable(false);
                    moTextAlternativeId.setEditable(false);
                    jtbNameFiscalCustomized.setEnabled(false);
                    
                    // organizations:
                    moTextName.setEditable(true);
                    moTextNameFiscal.setEditable(isReceiver);
                    moTextNameCapitalRegime.setEditable(isReceiver);
                    
                    // both entity types:
                    moRadNamePrintingPolicyName.setEnabled(isReceiver);
                    moRadNamePrintingPolicyNameFiscal.setEnabled(isReceiver);
                    break;
                    
                default:
                    // do nothing
            }
            
            // both entity types:
            moKeyTaxRegime.setEnabled(isReceiver);
            moTextAddressFiscal.setEnabled(isReceiver);
        }
    }

    private void actionIdentityType() {
        jbIdentityType.setEnabled(false);
        moKeyIdentityType.setEnabled(true);
        moKeyIdentityType.requestFocusInWindow();
    }

    private void actionSetDefaultFiscalId() {
        moTextFiscalId.setValue(DCfdConsts.RFC_GEN_NAC);
        moTextFiscalId.requestFocusInWindow();
    }

    private void actionXmlAddendaType() {
        jbXmlAddendaType.setEnabled(false);
        moKeyXmlAddendaType.setEnabled(true);
        moKeyXmlAddendaType.requestFocusInWindow();
    }

    private void actionCurrency() {
        jbCurrency.setEnabled(false);
        moKeyCurrency.setEnabled(true);
        moKeyCurrency.requestFocusInWindow();
    }
    
    private void itemStateKeyIdentityType() {
        // persons:
        moTextLastname.resetField();
        moTextFirstname.resetField();
        moTextAlternativeId.resetField();
        jtbNameFiscalCustomized.setSelected(false);
        itemStateNameFiscalCustomized();

        // organizations:
        moTextName.resetField();
        moTextNameFiscal.resetField();
        moTextNameCapitalRegime.resetField();

        // both entity types:
        bgNamePrintingPolicy.clearSelection();
        moKeyTaxRegime.removeAllItems();
        moTextAddressFiscal.resetField();

        if (moKeyIdentityType.getSelectedIndex() > 0) {
            bgNamePrintingPolicy.setSelected(moRadNamePrintingPolicyNameFiscal.getModel(), true);
            miClient.getSession().populateCatalogue(moKeyTaxRegime, DModConsts.CS_TAX_REG, moKeyIdentityType.getValue()[0], null);
            
            if (!isReceiver()) {
                moKeyTaxRegime.setValue(new int[] { DModSysConsts.CS_TAX_REG_NA });
            }
        }
        
        updateStatusFieldsIdentityType();
    }

    private void itemStateKeyBizPartnerType() {
        DDbBizPartnerType type = null;

        if (moKeyBizPartnerType.getSelectedIndex() > 0 && (!moBoolCreditByUser.getValue() || !moBoolAbpBizPartnerByUser.getValue())) {
            type = (DDbBizPartnerType) miClient.getSession().readRegistry(DModConsts.BU_BPR_TP, moKeyBizPartnerType.getValue());
        }

        if (!moBoolCreditByUser.getValue()) {
            if (moKeyBizPartnerType.getSelectedIndex() <= 0) {
                moKeyCreditType.resetField();
                moCurCreditLimit.getField().resetField();
                moIntCreditDays.resetField();
                moIntCreditDaysGrace.resetField();
                
                moKeyModeOfPaymentType.resetField();
                moKeyCfdUsage.resetField();
            }
            else {
                moKeyCreditType.setValue( new int[] { type.getFkCreditTypeId() });
                moCurCreditLimit.getField().setValue(type.getCreditLimit());
                moIntCreditDays.setValue(type.getCreditDays());
                moIntCreditDaysGrace.setValue(type.getCreditDaysGrace());
                
                if (isReceiver()) {
                    moKeyModeOfPaymentType.setValue( new int[] { type.getFkModeOfPaymentTypeId() });
                    moKeyCfdUsage.setValue( new int[] { moXmlCatalogCfdUsage.getId(type.getCfdUsage()) });
                }
                else {
                    moKeyModeOfPaymentType.resetField();
                    moKeyCfdUsage.resetField();
                }
            }
        }

        if (!moBoolAbpBizPartnerByUser.getValue()) {
            if (moKeyBizPartnerType.getSelectedIndex() <= 0) {
                moKeyAbpBizPartner.resetField();
            }
            else {
                moKeyAbpBizPartner.setValue(new int[] { type.getFkAbpBizPartnerId() });
            }
        }
    }

    private void itemStateKeyCreditType() {
        if (moKeyCreditType.getSelectedIndex() <= 0) {
            moCurCreditLimit.getField().setEditable(false);
            moIntCreditDays.setEditable(false);
            moIntCreditDaysGrace.setEditable(false);

            moCurCreditLimit.getField().resetField();
            moIntCreditDays.resetField();
            moIntCreditDaysGrace.resetField();
        }
        else {
            switch (moKeyCreditType.getValue()[0]) {
                case DModSysConsts.BS_CDT_TP_CDT_NON:
                    moCurCreditLimit.getField().setEditable(false);
                    moIntCreditDays.setEditable(false);
                    moIntCreditDaysGrace.setEditable(false);

                    moCurCreditLimit.getField().resetField();
                    moIntCreditDays.resetField();
                    moIntCreditDaysGrace.resetField();
                    break;

                case DModSysConsts.BS_CDT_TP_CDT_LIM_YES:
                    moCurCreditLimit.getField().setEditable(moBoolCreditByUser.getValue());
                    moIntCreditDays.setEditable(moBoolCreditByUser.getValue());
                    moIntCreditDaysGrace.setEditable(moBoolCreditByUser.getValue());
                    break;

                case DModSysConsts.BS_CDT_TP_CDT_LIM_NON:
                    moCurCreditLimit.getField().setEditable(false);
                    moIntCreditDays.setEditable(moBoolCreditByUser.getValue());
                    moIntCreditDaysGrace.setEditable(moBoolCreditByUser.getValue());

                    moCurCreditLimit.getField().resetField();
                    break;
                    
                default:
                    // nothing
            }
        }
    }

    private void itemStateBoolAgent() {
        if (moBoolAgent.isSelected()) {
            moKeyAgentType.setEnabled(true);
        }
        else {
            moKeyAgentType.setEnabled(false);
            if (moRegistry.getChildAgentConfig() == null) {
                moKeyAgentType.resetField();
            }
        }
    }

    private void itemStateBoolCreditByUser() {
        boolean isReceiver = isReceiver();
        
        moKeyCreditType.setEnabled(moBoolCreditByUser.getValue());
        moKeyModeOfPaymentType.setEnabled(moBoolCreditByUser.getValue() && isReceiver);
        moKeyCfdUsage.setEnabled(moBoolCreditByUser.getValue() && isReceiver);
        
        itemStateKeyBizPartnerType();
        itemStateKeyCreditType();
    }

    private void itemStateBoolAbpBizPartnerByUser() {
        DDbBizPartnerType type = null;

        if (moKeyBizPartnerType.getSelectedIndex() > 0) {
            type = (DDbBizPartnerType) miClient.getSession().readRegistry(DModConsts.BU_BPR_TP, moKeyBizPartnerType.getValue());
        }

        moKeyAbpBizPartner.setEnabled(moBoolAbpBizPartnerByUser.getValue());

        if (!moBoolAbpBizPartnerByUser.getValue()) {
            if (moKeyBizPartnerType.getSelectedIndex() <= 0) {
                moKeyAbpBizPartner.resetField();
            }
            else {
                moKeyAbpBizPartner.setValue(new int[] { type.getFkAbpBizPartnerId() });
            }
        }
    }
    
    private void itemStateNameFiscalCustomized() {
        if (isCustomer() && moKeyIdentityType.getSelectedIndex() > 0 && moKeyIdentityType.getValue()[0] == DModSysConsts.BS_IDY_TP_PER) {
            if (jtbNameFiscalCustomized.isSelected()) {
                moTextNameFiscal.setEditable(true);
                
                moRadNamePrintingPolicyName.setEnabled(true);
                moRadNamePrintingPolicyNameFiscal.setEnabled(true);
            }
            else {
                moTextNameFiscal.setEditable(false);
                
                moRadNamePrintingPolicyName.setEnabled(false);
                moRadNamePrintingPolicyNameFiscal.setEnabled(false);
                
                moRadNamePrintingPolicyNameFiscal.setSelected(true);
                
                focusLostNamePerson();
            }
        }
    }
    
    private void focusLostNamePerson() {
        if (moTextLastname.getValue().isEmpty() && moTextFirstname.getValue().isEmpty()) {
            moTextName.setValue("");
        }
        else {
            moTextName.setValue(DLibUtils.textTrim(moTextLastname.getValue() + ", " + moTextFirstname.getValue()));
        }
        
        if (!jtbNameFiscalCustomized.isSelected()) {
            moTextNameFiscal.setValue(DLibUtils.textTrim(moTextFirstname.getValue() + " " + moTextLastname.getValue()));
        }
        
        moTextNameCapitalRegime.setValue("");
    }
    
    private void focusLostNameOrganization() {
        if (!isCustomer()) {
            moTextNameFiscal.setValue(moTextName.getValue());
            moTextNameCapitalRegime.setValue("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgNamePrintingPolicy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JButton jbCurrency;
    private javax.swing.JButton jbIdentityType;
    private javax.swing.JButton jbSetDefaultFiscalId;
    private javax.swing.JButton jbXmlAddendaType;
    private javax.swing.JLabel jlAbpBizPartner;
    private javax.swing.JLabel jlAddressFiscal;
    private javax.swing.JLabel jlAddressFiscalInfo;
    private javax.swing.JLabel jlAgentType;
    private javax.swing.JLabel jlBizPartnerType;
    private javax.swing.JLabel jlCfdUsage;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlCodeOwn;
    private javax.swing.JLabel jlCodeOwnInfo;
    private javax.swing.JLabel jlCreditDays;
    private javax.swing.JLabel jlCreditDaysGrace;
    private javax.swing.JLabel jlCreditLimit;
    private javax.swing.JLabel jlCreditType;
    private javax.swing.JLabel jlCurrency;
    private javax.swing.JLabel jlDateEnd;
    private javax.swing.JLabel jlDateStart;
    private javax.swing.JLabel jlEmissionType;
    private javax.swing.JLabel jlFirstname;
    private javax.swing.JLabel jlFiscalId;
    private javax.swing.JLabel jlFiscalId1;
    private javax.swing.JLabel jlForeignId;
    private javax.swing.JLabel jlForeignIdInfo;
    private javax.swing.JLabel jlLastname;
    private javax.swing.JLabel jlModeOfPaymentType;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlNameFiscal;
    private javax.swing.JLabel jlNameFiscalHellp;
    private javax.swing.JLabel jlNameHelp;
    private javax.swing.JLabel jlNameSeparator;
    private javax.swing.JLabel jlNickname;
    private javax.swing.JLabel jlNote;
    private javax.swing.JLabel jlTaxRegime;
    private javax.swing.JLabel jlWeb;
    private javax.swing.JLabel jlXmlAddendaType;
    private javax.swing.JPanel jpConfig;
    private javax.swing.JPanel jpConfig1;
    private javax.swing.JPanel jpConfig11;
    private javax.swing.JPanel jpConfig12;
    private javax.swing.JPanel jpConfig2;
    private javax.swing.JPanel jpRegistry;
    private javax.swing.JPanel jpRegistry1;
    private javax.swing.JPanel jpRegistry11;
    private javax.swing.JPanel jpRegistry12;
    private javax.swing.JPanel jpRegistry2;
    private javax.swing.JToggleButton jtbNameFiscalCustomized;
    private sba.lib.gui.bean.DBeanFieldBoolean moBoolAbpBizPartnerByUser;
    private sba.lib.gui.bean.DBeanFieldBoolean moBoolAgent;
    private sba.lib.gui.bean.DBeanFieldBoolean moBoolBank;
    private sba.lib.gui.bean.DBeanFieldBoolean moBoolCarrier;
    private sba.lib.gui.bean.DBeanFieldBoolean moBoolCreditByUser;
    private sba.lib.gui.bean.DBeanFieldBoolean moBoolFiscalHomologous;
    private sba.lib.gui.bean.DBeanCompoundFieldCurrency moCurCreditLimit;
    private sba.lib.gui.bean.DBeanFieldDate moDateEnd;
    private sba.lib.gui.bean.DBeanFieldDate moDateStart;
    private sba.lib.gui.bean.DBeanFieldInteger moIntCreditDays;
    private sba.lib.gui.bean.DBeanFieldInteger moIntCreditDaysGrace;
    private sba.lib.gui.bean.DBeanFieldKey moKeyAbpBizPartner;
    private sba.lib.gui.bean.DBeanFieldKey moKeyAgentType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyBizPartnerType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyCfdUsage;
    private sba.lib.gui.bean.DBeanFieldKey moKeyCreditType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyCurrency;
    private sba.lib.gui.bean.DBeanFieldKey moKeyEmissionType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyIdentityType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyModeOfPaymentType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyTaxRegime;
    private sba.lib.gui.bean.DBeanFieldKey moKeyXmlAddendaType;
    private sba.mod.bpr.form.DPanelBranch moPanelBranch;
    private sba.mod.bpr.form.DPanelBranchAddress moPanelBranchAddress;
    private sba.lib.gui.bean.DBeanFieldRadio moRadNamePrintingPolicyName;
    private sba.lib.gui.bean.DBeanFieldRadio moRadNamePrintingPolicyNameFiscal;
    private sba.lib.gui.bean.DBeanFieldText moTextAddressFiscal;
    private sba.lib.gui.bean.DBeanFieldText moTextAlternativeId;
    private sba.lib.gui.bean.DBeanFieldText moTextCode;
    private sba.lib.gui.bean.DBeanFieldText moTextCodeOwn;
    private sba.lib.gui.bean.DBeanFieldText moTextFirstname;
    private sba.lib.gui.bean.DBeanFieldText moTextFiscalId;
    private sba.lib.gui.bean.DBeanFieldText moTextForeignId;
    private sba.lib.gui.bean.DBeanFieldText moTextLastname;
    private sba.lib.gui.bean.DBeanFieldText moTextName;
    private sba.lib.gui.bean.DBeanFieldText moTextNameCapitalRegime;
    private sba.lib.gui.bean.DBeanFieldText moTextNameFiscal;
    private sba.lib.gui.bean.DBeanFieldText moTextNickname;
    private sba.lib.gui.bean.DBeanFieldText moTextNote;
    private sba.lib.gui.bean.DBeanFieldText moTextWeb;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addAllListeners() {
        jbIdentityType.addActionListener(this);
        jbSetDefaultFiscalId.addActionListener(this);
        jbXmlAddendaType.addActionListener(this);
        jbCurrency.addActionListener(this);
        
        jtbNameFiscalCustomized.addItemListener(this);
        moKeyIdentityType.addItemListener(this);
        moKeyBizPartnerType.addItemListener(this);
        moKeyCreditType.addItemListener(this);
        moBoolAgent.addItemListener(this);
        moBoolCreditByUser.addItemListener(this);
        moBoolAbpBizPartnerByUser.addItemListener(this);
        
        moTextLastname.addFocusListener(this);
        moTextFirstname.addFocusListener(this);
        moTextName.addFocusListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbIdentityType.removeActionListener(this);
        jbSetDefaultFiscalId.removeActionListener(this);
        jbXmlAddendaType.removeActionListener(this);
        jbCurrency.removeActionListener(this);
        
        jtbNameFiscalCustomized.removeItemListener(this);
        moKeyIdentityType.removeItemListener(this);
        moKeyBizPartnerType.removeItemListener(this);
        moKeyCreditType.removeItemListener(this);
        moBoolAgent.removeItemListener(this);
        moBoolCreditByUser.removeItemListener(this);
        moBoolAbpBizPartnerByUser.removeItemListener(this);
        
        moTextLastname.removeFocusListener(this);
        moTextFirstname.removeFocusListener(this);
        moTextName.removeFocusListener(this);
    }

    @Override
    public void reloadCatalogues() {
        miClient.getSession().populateCatalogue(moKeyIdentityType, DModConsts.BS_IDY_TP, 0, null);
        miClient.getSession().populateCatalogue(moKeyBizPartnerType, DModConsts.BU_BPR_TP, mnBizPartnerClass, null);
        miClient.getSession().populateCatalogue(moKeyAgentType, DModConsts.MU_AGT_TP, 0, null);
        miClient.getSession().populateCatalogue(moKeyEmissionType, DModConsts.TS_EMI_TP, 0, null);
        miClient.getSession().populateCatalogue(moKeyXmlAddendaType, DModConsts.TS_XML_ADD_TP, 0, null);
        miClient.getSession().populateCatalogue(moKeyCurrency, DModConsts.CS_CUR, 0, null);
        miClient.getSession().populateCatalogue(moKeyCreditType, DModConsts.BS_CDT_TP, 0, null);
        miClient.getSession().populateCatalogue(moKeyModeOfPaymentType, DModConsts.FS_MOP_TP, 0, null);
        miClient.getSession().populateCatalogue(moKeyAbpBizPartner, DModConsts.F_ABP_BPR, 0, null);
    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        DDbBizPartnerConfig config = null;
        DDbBranch branch = null;
        DDbBranchAddress branchAddress = null;
        Vector<DGridRow> addresses = new Vector<>();

        moRegistry = (DDbBizPartner) registry;

        mnFormResult = 0;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        switch (mnBizPartnerClass) {
            case DModSysConsts.BS_BPR_CL_VEN:
                moRegistry.setVendor(true);
                break;
            case DModSysConsts.BS_BPR_CL_CUS:
                moRegistry.setCustomer(true);
                break;
            case DModSysConsts.BS_BPR_CL_CDR:
                moRegistry.setCreditor(true);
                break;
            case DModSysConsts.BS_BPR_CL_DBR:
                moRegistry.setDebtor(true);
                break;
            default:
                miClient.showMsgBoxError(DLibConsts.ERR_MSG_OPTION_UNKNOWN);
        }

        if (moRegistry.isRegistryNew()) {
            moRegistry.initPrimaryKey();
            jtfRegistryKey.setText("");

            config = moRegistry.getChildConfig(mnBizPartnerClass);

            if (config == null) {
                config = new DDbBizPartnerConfig();
                config.setPkBizPartnerClassId(mnBizPartnerClass);
                config.setDateStart(DLibTimeUtils.getBeginOfMonth(miClient.getSession().getWorkingDate()));
                config.setDateEnd_n(null);
                config.setFkBizPartnerClassId(mnBizPartnerClass);
                config.setFkBizPartnerTypeId(1);
                moRegistry.getChildConfigs().add(config);
            }

            moRegistry.getChildConfig(mnBizPartnerClass).setCode("");

            if (moRegistry.getChildBranches().isEmpty()) {
                branchAddress = new DDbBranchAddress();
                branchAddress.setDefault(true);

                branch = new DDbBranch();
                branch.setAddressPrintable(true);
                branch.getChildAddresses().add(branchAddress);

                moRegistry.getChildBranches().add(branch);
            }

            if (moRegistry.getFkEmissionTypeId() == 0) {
                moRegistry.setFkEmissionTypeId(DModSysConsts.TS_EMI_TP_BPR);
            }

            if (moRegistry.getFkXmlAddendaTypeId() == 0) {
                moRegistry.setFkXmlAddendaTypeId(DModSysConsts.TS_XML_ADD_TP_NA);
            }
            
            if (moRegistry.getFkTaxRegimeId() == 0) {
                moRegistry.setFkTaxRegimeId(DModSysConsts.CS_TAX_REG_NA);
            }
        }
        else {
            jtfRegistryKey.setText(DLibUtils.textKey(moRegistry.getPrimaryKey()));

            config = moRegistry.getChildConfig(mnBizPartnerClass);
        }

        moTextCode.setValue(config.getCode());
        moKeyIdentityType.setValue(new int[] { moRegistry.getFkIdentityTypeId() });
        itemStateKeyIdentityType();
        moTextLastname.setValue(moRegistry.getLastname());
        moTextFirstname.setValue(moRegistry.getFirstname());
        moTextName.setValue(moRegistry.getName());
        jtbNameFiscalCustomized.setSelected(moRegistry.isNameFiscalCustomized()); // may dispatch event that can change fiscal name
        itemStateNameFiscalCustomized();
        moTextNameFiscal.setValue(moRegistry.getNameFiscal());
        moTextNameCapitalRegime.setValue(moRegistry.getNameCapitalRegime());
        if (moRegistry.isNamePrintingPolicyForFiscal()) {
            moRadNamePrintingPolicyNameFiscal.setSelected(true);
        }
        else {
            moRadNamePrintingPolicyName.setSelected(true);
        }
        moTextNickname.setValue(moRegistry.getNickname());
        moTextFiscalId.setValue(moRegistry.getFiscalId());
        moTextAlternativeId.setValue(moRegistry.getAlternativeId());
        moBoolFiscalHomologous.setValue(moRegistry.isFiscalHomologous());
        moTextNote.setValue(moRegistry.getNote());
        
        moKeyBizPartnerType.setValue(new int[] { config.getFkBizPartnerClassId(), config.getFkBizPartnerTypeId() });
        moDateStart.setValue(config.getDateStart());
        moDateEnd.setValue(config.getDateEnd_n());
        moTextCodeOwn.setValue(config.getCodeOwn());
        moTextForeignId.setValue(moRegistry.getForeignId());
        
        moBoolAgent.setValue(moRegistry.getChildAgentConfig() != null && !moRegistry.getChildAgentConfig().isDeleted());
        moKeyAgentType.setValue(new int[] { moRegistry.getChildAgentConfig() == null ? 0 : moRegistry.getChildAgentConfig().getFkAgentTypeId() });
        
        moBoolBank.setValue(moRegistry.isBank());
        moBoolCarrier.setValue(moRegistry.isCarrier());
        moKeyEmissionType.setValue(new int[] { moRegistry.getFkEmissionTypeId() });
        moKeyXmlAddendaType.setValue(new int[] { moRegistry.getFkXmlAddendaTypeId()});
        moKeyTaxRegime.setValue(new int[] { moRegistry.getFkTaxRegimeId()});
        moTextAddressFiscal.setValue(moRegistry.getAddressFiscal());
        moTextWeb.setValue(moRegistry.getWeb());

        moKeyCurrency.setValue(new int[] { config.getFkCurrencyId_n() });
        moBoolCreditByUser.setValue(config.isCreditByUser());
        moKeyCreditType.setValue(new int[] { config.getFkCreditTypeId_n() });
        moCurCreditLimit.getField().setValue(config.getCreditLimit());
        moIntCreditDays.setValue(config.getCreditDays());
        moIntCreditDaysGrace.setValue(config.getCreditDaysGrace());
        moKeyModeOfPaymentType.setValue(new int[] { config.getFkModeOfPaymentTypeId_n() });
        moKeyCfdUsage.setValue(new int[] { moXmlCatalogCfdUsage.getId(config.getCfdUsage()) });
        
        moBoolAbpBizPartnerByUser.setValue(config.getFkAbpBizPartnerId_n() != 0);
        moKeyAbpBizPartner.setValue(new int[] { config.getFkAbpBizPartnerId_n() });

        moPanelBranch.setRegistry(moRegistry.getChildBranchHeadquarters());
        moPanelBranchAddress.setRegistry(moRegistry.getChildBranchHeadquarters().getChildAddressOfficial());

        if (moRegistry.getChildBranchHeadquarters().getChildAddresses().size() > 1) {
            for (int i = 1; i < moRegistry.getChildBranchHeadquarters().getChildAddresses().size(); i++) {
                addresses.add(moRegistry.getChildBranchHeadquarters().getChildAddresses().get(i));
            }
        }

        moGridBranchAddresses.populateGrid(addresses);

        jTabbedPane.setSelectedIndex(0);
        
        setFormEditable(true);
        
        updateStatusFieldsIdentityType();
        itemStateKeyBizPartnerType();
        itemStateBoolAgent();
        itemStateKeyCreditType();
        itemStateBoolCreditByUser();
        itemStateBoolAbpBizPartnerByUser();
        
        // Prevent undesired modifications to identity type:
        if (moRegistry.isRegistryNew() && moRegistry.getFkIdentityTypeId() == 0) {
            moKeyIdentityType.setEnabled(true);
            jbIdentityType.setEnabled(false);
        }
        else {
            moKeyIdentityType.setEnabled(false);
            jbIdentityType.setEnabled(true);
        }

        // Enable code if appropriate:
        moTextCode.setEnabled(((DDbConfigCompany) miClient.getSession().getConfigCompany()).isCodeBizPartnerApplying());
        
        // Prevent undesired modifications to currency:
        jbCurrency.setEnabled(true);
        moKeyCurrency.setEnabled(false);

        // Prevent undesired modifications to XML-addenda type:
        
        boolean isReceiver = isReceiver();
        
        moKeyEmissionType.setEnabled(isReceiver);
        moKeyXmlAddendaType.setEnabled(false);
        jbXmlAddendaType.setEnabled(isReceiver);
        moKeyTaxRegime.setEnabled(isReceiver && moKeyBizPartnerType.getSelectedIndex() > 0);
        moTextAddressFiscal.setEnabled(isReceiver);
        
        addAllListeners();
    }

    @Override
    public DDbBizPartner getRegistry() throws Exception {
        DDbBizPartner registry = moRegistry.clone();
        DDbBizPartnerConfig config = null;

        if (registry.isRegistryNew()) { }

        registry.setName(moTextName.getValue());
        registry.setLastname(moTextLastname.getValue());
        registry.setFirstname(moTextFirstname.getValue());
        registry.setNameFiscal(moTextNameFiscal.getValue());
        registry.setNameCapitalRegime(moTextNameCapitalRegime.getValue());
        registry.setNamePrintingPolicy(moRadNamePrintingPolicyNameFiscal.isSelected() ? DModSysConsts.BPR_NAME_PRT_POL_NAME_FISCAL : DModSysConsts.BPR_NAME_PRT_POL_NAME);
        registry.setNickname(moTextNickname.getValue());
        registry.setFiscalId(moTextFiscalId.getValue());
        registry.setAlternativeId(moTextAlternativeId.getValue());
        registry.setForeignId(moTextForeignId.getValue());
        registry.setAddressFiscal(moTextAddressFiscal.isEnabled() ? moTextAddressFiscal.getValue() : "");
        registry.setWeb(moTextWeb.getValue());
        registry.setNote(moTextNote.getValue());
        registry.setNameFiscalCustomized(jtbNameFiscalCustomized.isSelected());
        registry.setFiscalHomologous(moBoolFiscalHomologous.getValue());
        registry.setBank(moBoolBank.getValue());
        registry.setCarrier(moBoolCarrier.getValue());
        registry.setFkIdentityTypeId(moKeyIdentityType.getValue()[0]);
        registry.setFkEmissionTypeId(moKeyEmissionType.getValue()[0]);
        registry.setFkTaxRegimeId(moKeyTaxRegime.getValue()[0]);
        registry.setFkXmlAddendaTypeId(moKeyXmlAddendaType.getValue()[0]);

        config = registry.getChildConfig(mnBizPartnerClass);

        config.setCode(moTextCode.getValue());
        config.setCodeOwn(moTextCodeOwn.getValue());
        config.setDateStart(moDateStart.getValue());
        config.setDateEnd_n(moDateEnd.getValue());
        config.setFkBizPartnerClassId(moKeyBizPartnerType.getValue()[0]);
        config.setFkBizPartnerTypeId(moKeyBizPartnerType.getValue()[1]);
        config.setFkCurrencyId_n(moKeyCurrency.getSelectedIndex() <= 0 ? 0 : moKeyCurrency.getValue()[0]);

        if (!moBoolCreditByUser.getValue()) {
            config.setCreditByUser(false);
            config.setCreditLimit(0);
            config.setCreditDays(0);
            config.setCreditDaysGrace(0);
            config.setCfdUsage("");
            config.setFkCreditTypeId_n(0);
            config.setFkModeOfPaymentTypeId_n(0);
        }
        else {
            config.setCreditByUser(true);
            config.setCreditLimit(moCurCreditLimit.getField().getValue());
            config.setCreditDays(moIntCreditDays.getValue());
            config.setCreditDaysGrace(moIntCreditDaysGrace.getValue());
            config.setCfdUsage(!moKeyCfdUsage.isEnabled() || moKeyCfdUsage.getSelectedIndex() <= 0 ? "" : moXmlCatalogCfdUsage.getCode(moKeyCfdUsage.getValue()[0]));
            config.setFkCreditTypeId_n(moKeyCreditType.getValue()[0]);
            config.setFkModeOfPaymentTypeId_n(!moKeyModeOfPaymentType.isEnabled() || moKeyModeOfPaymentType.getSelectedIndex() <= 0 ? 0 : moKeyModeOfPaymentType.getValue()[0]);
        }

        if (!moBoolAgent.getValue()) {
            if (registry.getChildAgentConfig() != null) {
                registry.getChildAgentConfig().setDeleted(true);
            }
        }
        else {
            if (registry.getChildAgentConfig() == null) {
                registry.setChildAgentConfig(new DDbAgentConfig());
            }
            registry.getChildAgentConfig().setDeleted(false);
            registry.getChildAgentConfig().setFkAgentTypeId(moKeyAgentType.getValue()[0]);
        }

        if (!moBoolAbpBizPartnerByUser.getValue()) {
            config.setFkAbpBizPartnerId_n(0);
        }
        else {
            config.setFkAbpBizPartnerId_n(moKeyAbpBizPartner.getValue()[0]);
        }

        registry.getChildBranches().set(0, moPanelBranch.getRegistry());
        registry.getChildBranchHeadquarters().getChildAddresses().set(0, moPanelBranchAddress.getRegistry());

        while (registry.getChildBranchHeadquarters().getChildAddresses().size() > 1) {
            registry.getChildBranchHeadquarters().getChildAddresses().remove(1);
        }

        for (int i = 0; i < moGridBranchAddresses.getModel().getGridRows().size(); i++) {
            registry.getChildBranchHeadquarters().getChildAddresses().add((DDbBranchAddress) moGridBranchAddresses.getModel().getGridRows().get(i));
        }

        return registry;
    }

    @Override
    public DGuiValidation validateForm() {
        DGuiValidation validation = moFields.validateFields();

        if (validation.isValid()) {
            validation = moPanelBranch.validatePanel();
            validation.setTabbedPane(jTabbedPane);
            validation.setTab(0);

            if (validation.isValid()) {
                validation = moPanelBranchAddress.validatePanel();
                validation.setTabbedPane(jTabbedPane);
                validation.setTab(0);

                if (validation.isValid()) {
                    try {
                        int count = 0;
                        
                        if (moPanelBranchAddress.getRegistry().isDefault()) {
                            count++;
                        }

                        for (DGridRow row : moGridBranchAddresses.getModel().getGridRows()) {
                            if (((DDbBranchAddress) row).isDefault()) {
                                count++;
                            }
                        }

                        if (count == 0) {
                            validation.setMessage("Se debe especificar cuál es el domicilio por default.");
                        }
                        else if (count > 1){
                            validation.setMessage("Se debe especificar solamente un domicilio por default.");
                        }
                    }
                    catch (Exception e) {
                        validation.setMessage(e.toString());
                    }
                }
            }
        }

        return validation;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();

            if (button == jbIdentityType) {
                actionIdentityType();
            }
            else if (button == jbSetDefaultFiscalId) {
                actionSetDefaultFiscalId();
            }
            else if (button == jbXmlAddendaType) {
                actionXmlAddendaType();
            }
            else if (button == jbCurrency) {
                actionCurrency();
            }
        }
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof DBeanFieldKey) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                DBeanFieldKey field = (DBeanFieldKey) e.getSource();

                if (field == moKeyIdentityType) {
                    itemStateKeyIdentityType();
                }
                else if (field == moKeyBizPartnerType) {
                    itemStateKeyBizPartnerType();
                }
                else if (field == moKeyCreditType) {
                    itemStateKeyCreditType();
                }
            }
        }
        else if (e.getSource() instanceof DBeanFieldBoolean) {
            DBeanFieldBoolean field = (DBeanFieldBoolean) e.getSource();

            if (field == moBoolAgent) {
                itemStateBoolAgent();
            }
            else if (field == moBoolCreditByUser) {
                itemStateBoolCreditByUser();
            }
            else if (field == moBoolAbpBizPartnerByUser) {
                itemStateBoolAbpBizPartnerByUser();
            }
        }
        else if (e.getSource() instanceof JToggleButton) {
            JToggleButton toggleButton = (JToggleButton) e.getSource();
            
            if (toggleButton == jtbNameFiscalCustomized) {
                itemStateNameFiscalCustomized();
            }
        }
    }

    @Override
    public void focusGained(FocusEvent e) {
        
    }

    @Override
    public void focusLost(FocusEvent e) {
        if (e.getSource() instanceof DBeanFieldText) {
            DBeanFieldText field = (DBeanFieldText) e.getSource();
            
            if (field == moTextLastname || field == moTextFirstname) {
                focusLostNamePerson();
            }
            else if (field == moTextName) {
                focusLostNameOrganization();
            }
        }
    }
}
